// TruthEngine360 Master Research Database Index v1.0
// 565 sources | 22 sections | AUMER Foundation | May 20, 2026
// access: open | key | foia | manual | sub
// priority: CRITICAL | HIGH | MEDIUM | LOW

export const SECTIONS = [
  { id: 1,  name: "US Federal: Military & Defense",        count: 45, priority: "CRITICAL", country: "US" },
  { id: 2,  name: "US Federal: Immigration & Enforcement", count: 38, priority: "CRITICAL", country: "US" },
  { id: 3,  name: "US Federal: Veterans Affairs",          count: 22, priority: "CRITICAL", country: "US" },
  { id: 4,  name: "US Intelligence: Declassified",         count: 18, priority: "HIGH",     country: "US" },
  { id: 5,  name: "US Federal: Legislative & Regulatory",  count: 28, priority: "HIGH",     country: "US" },
  { id: 6,  name: "US Federal: Demographics & Census",     count: 24, priority: "HIGH",     country: "US" },
  { id: 7,  name: "US Federal: Courts & Legal",            count: 20, priority: "HIGH",     country: "US" },
  { id: 8,  name: "US Federal: Health & Social",           count: 16, priority: "MEDIUM",   country: "US" },
  { id: 9,  name: "US State & Local",                      count: 42, priority: "HIGH",     country: "US" },
  { id: 10, name: "Mexico Federal Government",             count: 38, priority: "CRITICAL", country: "MX" },
  { id: 11, name: "Mexico State & Local",                  count: 24, priority: "MEDIUM",   country: "MX" },
  { id: 12, name: "Mexico Academic Repositories",          count: 20, priority: "HIGH",     country: "MX" },
  { id: 13, name: "US Academic Repositories",              count: 32, priority: "HIGH",     country: "US" },
  { id: 14, name: "Think Tanks & Research Organizations",  count: 28, priority: "HIGH",     country: "INT" },
  { id: 15, name: "NGO, Shelters & Advocacy",              count: 30, priority: "CRITICAL", country: "INT" },
  { id: 16, name: "Legal Databases",                       count: 18, priority: "HIGH",     country: "US" },
  { id: 17, name: "Newspaper, Press & Media Archives",     count: 26, priority: "MEDIUM",   country: "INT" },
  { id: 18, name: "Genealogy & Civil Records",             count: 22, priority: "HIGH",     country: "INT" },
  { id: 19, name: "International Organizations",           count: 20, priority: "MEDIUM",   country: "INT" },
  { id: 20, name: "Scholarly Aggregators & Databases",     count: 24, priority: "HIGH",     country: "INT" },
  { id: 21, name: "Geospatial & GIS",                      count: 16, priority: "MEDIUM",   country: "INT" },
  { id: 22, name: "DACA & Immigration Reform",             count: 14, priority: "HIGH",     country: "US" },
];

export const CONNECTOR_QUEUE = [
  { rank: 1,  id: "dcas",             name: "DCAS/NARA Catalog",     api: "https://catalog.archives.gov/api/v1/", auth: "None" },
  { rank: 2,  id: "congress",         name: "Congress.gov",          api: "https://api.congress.gov/v3/",         auth: "API Key" },
  { rank: 3,  id: "census",           name: "US Census",             api: "https://api.census.gov/data/",         auth: "API Key" },
  { rank: 4,  id: "foia_gov",         name: "FOIA.gov",              api: "https://api.foia.gov/",                auth: "API Key" },
  { rank: 5,  id: "usaspending",      name: "USAspending",           api: "https://api.usaspending.gov/",         auth: "None" },
  { rank: 6,  id: "inegi",            name: "INEGI Mexico",          api: "https://www.inegi.org.mx/servicios/api_indicadores.html", auth: "Token" },
  { rank: 7,  id: "loc",              name: "Library of Congress",   api: "https://www.loc.gov/apis/",            auth: "None" },
  { rank: 8,  id: "chronicling",      name: "Chronicling America",   api: "https://chroniclingamerica.loc.gov/api/", auth: "None" },
  { rank: 9,  id: "govinfo",          name: "GovInfo",               api: "https://api.govinfo.gov",              auth: "API Key" },
  { rank: 10, id: "data_gov",         name: "Data.gov",              api: "https://catalog.data.gov/api/3/",      auth: "None" },
  { rank: 11, id: "federal_register", name: "Federal Register",      api: "https://www.federalregister.gov/api/v1/", auth: "None" },
  { rank: 12, id: "bls",             name: "Bureau of Labor Stats",  api: "https://api.bls.gov/publicAPI/v2/",   auth: "API Key" },
  { rank: 13, id: "openalex",        name: "OpenAlex",               api: "https://api.openalex.org/",           auth: "None" },
  { rank: 14, id: "crossref",        name: "Crossref",               api: "https://api.crossref.org/",           auth: "None" },
  { rank: 15, id: "familysearch",    name: "FamilySearch",           api: "https://api.familysearch.org/",        auth: "OAuth" },
  { rank: 16, id: "harvard_dv",      name: "Harvard Dataverse",      api: "https://dataverse.harvard.edu/api/",  auth: "API Key" },
  { rank: 17, id: "courtlistener",   name: "CourtListener",          api: "https://www.courtlistener.com/api/",  auth: "None" },
  { rank: 18, id: "datos_mx",        name: "datos.gob.mx",           api: "https://www.datos.gob.mx/api/3/",     auth: "None" },
  { rank: 19, id: "pnt_mx",          name: "PNT Mexico",             api: "https://consultapublicamx.plataformadetransparencia.org.mx", auth: "INAI" },
  { rank: 20, id: "banxico",         name: "Banxico",                api: "https://www.banxico.org.mx/SieAPIRest/service/v1/", auth: "Token" },
  { rank: 21, id: "trac",            name: "TRAC Immigration",       api: "https://trac.syr.edu",                auth: "None" },
  { rank: 22, id: "propublica",      name: "ProPublica Data",        api: "https://www.propublica.org/datastore/", auth: "API Key" },
  { rank: 23, id: "semantic_scholar",name: "Semantic Scholar",       api: "https://api.semanticscholar.org",     auth: "None" },
  { rank: 24, id: "icpsr",           name: "ICPSR",                  api: "https://www.icpsr.umich.edu/icpsrweb/ICPSR/access/", auth: "Token" },
  { rank: 25, id: "core",            name: "CORE Open Research",     api: "https://api.core.ac.uk",              auth: "API Key" },
];

// All 565 sources — compact format: [n, sec, name, url, access, country, data, use]
// access: "open"|"key"|"foia"|"manual"|"sub"
export const SOURCES_RAW = [
  // SECTION 1 — US Federal: Military & Defense (1-45)
  [1,1,"DCAS Defense Casualty Analysis System","https://catalog.archives.gov/id/2240992","open","US","58,220 Vietnam KIA records","PRIMARY forensic target"],
  [2,1,"NARA Catalog API","https://catalog.archives.gov","open","US","Archival descriptive metadata","All military record searches"],
  [3,1,"NARA AAD Access to Archival Databases","https://aad.archives.gov","open","US","Structured military datasets","DCAS, SEADOGS, etc."],
  [4,1,"NARA Veterans Service Records","https://www.archives.gov/veterans","open","US","DD-214, SF-180 requests","Veteran verification"],
  [5,1,"NARA eVetRecs","https://evetrecs.archives.gov","key","US","Military personnel records","Individual case verification"],
  [6,1,"NARA-St. Louis NPRC","https://www.archives.gov/st-louis","manual","US","Army/Navy/Marine records","Form 102 SSS, DD-214"],
  [7,1,"DoD DMDC Defense Manpower Data Center","https://dwp.dmdc.osd.mil","key","US","Active/reserve personnel","Non-citizen service verification"],
  [8,1,"DoD Public Data Listing","https://data.defense.gov","open","US","DoD datasets catalog","Military demographics"],
  [9,1,"DoD Military Casualty Affairs","https://www.dmdc.osd.mil/mco","foia","US","KIA transfer records","Casualty remains documentation"],
  [10,1,"DoD History Office","https://history.defense.gov","open","US","Historical documents","Vietnam-era policy records"],
  [11,1,"Army Center of Military History","https://history.army.mil","open","US","Unit histories, after-action","Vietnam combat unit records"],
  [12,1,"Army Human Resources Command","https://www.hrc.army.mil","foia","US","Personnel records","Service verification"],
  [13,1,"Marine Corps History Division","https://www.usmcu.edu","manual","US","Unit diaries, casualty lists","Marine KIA forensics"],
  [14,1,"Navy History and Heritage Command","https://www.history.navy.mil","manual","US","Muster rolls, deck logs","Navy non-citizen service"],
  [15,1,"Air Force Historical Research Agency","https://www.afhra.af.mil","manual","US","Unit histories","Air Force KIA records"],
  [16,1,"Defense Technical Information Center (DTIC)","https://www.dtic.mil","key","US","Technical/research reports","Vietnam-era DoD studies"],
  [17,1,"Pentagon Papers (National Security Archive)","https://nsarchive.gwu.edu","open","US","Declassified DoD docs","Vietnamization, casualty policy"],
  [18,1,"Selective Service System","https://www.sss.gov","open","US","Draft registration records","Non-citizen draftee verification"],
  [19,1,"SSS Status Information Letters","https://www.sss.gov/verify/","open","US","Draft status verification","Vietnam-era draft eligibility"],
  [20,1,"SSS Form 102 (NARA-St. Louis)","https://www.archives.gov/st-louis","foia","US","Non-citizen alien registration","KEY: non-citizen draftee ID"],
  [21,1,"NARA SEADOGS","https://aad.archives.gov/aad/series-description.jsp?s=578","open","US","Vietnam-era combat deaths","Cross-reference with DCAS"],
  [22,1,"Vietnam Veterans Memorial Fund Database","https://www.vvmf.org","open","US","58,318 names on the Wall","Wall verification — 5 Mexico names"],
  [23,1,"DoD Prisoner of War/MIA (DPAA)","https://www.dpaa.mil","open","US","POW/MIA case files","Missing personnel cross-ref"],
  [24,1,"DPAA Defense POW/MIA Accounting","https://dpaa.mil","open","US","Unaccounted personnel","Vietnam-era missing cases"],
  [25,1,"Medal of Honor Citation Database","https://www.cmohs.org","open","US","MOH citations, dates","Recognition latency analysis"],
  [26,1,"Army Decorations Repository","https://www.hrc.army.mil","open","US","Service medals, commendations","Recognition latency"],
  [27,1,"DoD FY Manpower Statistics","https://open.defense.gov","open","US","Active duty demographics","Non-citizen service proportions"],
  [28,1,"DEOMI Defense Equal Opportunity","https://www.deomi.org","manual","US","Racial equity military data","Disproportionality analysis"],
  [29,1,"RAND Corporation Military Research","https://www.rand.org","open","US","Research reports","Military demographics, draft equity"],
  [30,1,"Army Surgeon General Casualty Reports (RG112)","https://catalog.archives.gov/id/654928","open","US","Medical/casualty records","Vietnam KIA cause analysis"],
  [31,1,"NARA RG319 (Army Intelligence)","https://catalog.archives.gov/id/593411","open","US","Army operational records","Vietnam combat unit data"],
  [32,1,"NARA RG407 (Adjutant General)","https://catalog.archives.gov","open","US","Personnel/casualty files","Vietnam-era Army records"],
  [33,1,"NARA RG127 (Marine Corps)","https://catalog.archives.gov","open","US","USMC operational records","Marine Corps KIA forensics"],
  [34,1,"Vietnam War Records (Military Reference Branch)","https://www.archives.gov/research/military/vietnam-war","manual","US","Vietnam-era records guide","Research pathway documentation"],
  [35,1,"Joint Chiefs of Staff Vietnam History","https://www.jcs.mil","foia","US","Command decisions","Vietnamization policy evidence"],
  [36,1,"MACV Records","https://catalog.archives.gov","open","US","Operational reports","Casualty reporting changes"],
  [37,1,"National Defense Authorization Act Database","https://www.congress.gov","key","US","Legislative text","Veteran citizenship provisions"],
  [38,1,"Military.com Service Records Portal","https://www.military.com","manual","US","Veteran service verification","Case validation"],
  [39,1,"US Army Heritage and Education Center","https://ahec.armywarcollege.edu","manual","US","Vietnam oral histories, papers","Primary source documents"],
  [40,1,"DoD Inspector General Reports","https://www.dodig.mil","open","US","DoD audit reports","Accountability documentation"],
  [41,1,"Defense Finance and Accounting Service (DFAS)","https://www.dfas.mil","foia","US","Pay/benefits records","Veteran benefit deprivation"],
  [42,1,"GovInfo Congressional Record (Military)","https://www.govinfo.gov","key","US","Congressional Record text","Vietnam-era military debate"],
  [43,1,"National Defense University Research","https://ndu.edu","open","US","Defense research reports","Vietnam demographics research"],
  [44,1,"Westat Survey Research","https://www.westat.com","manual","US","Military population surveys","Hispanic service data"],
  [45,1,"SIPRI Military Expenditure Database","https://www.sipri.org","open","INT","International military spending","Vietnam-era US spending context"],
  // SECTION 2 — US Federal: Immigration & Enforcement (46-83)
  [46,2,"DHS/ICE ENFORCE Database","https://www.ice.gov/data","foia","US","Individual deportation records","CRITICAL: veteran removals"],
  [47,2,"DHS OHSS Immigration Yearbook","https://ohss.dhs.gov","open","US","Annual immigration statistics","Removal counts by year"],
  [48,2,"DHS OHSS Monthly Enforcement Tables","https://ohss.dhs.gov","open","US","Removal/detention monthly data","Trend analysis"],
  [49,2,"ICE ERO Statistical Datasets","https://www.ice.gov/statistics","open","US","ERO removals by country","Mexico-bound deportations"],
  [50,2,"ICE FOIA Reading Room","https://www.ice.gov/foia/library","open","US","Released FOIA documents","Prior veteran removal disclosures"],
  [51,2,"DHS FOIA Portal","https://www.dhs.gov/foia","foia","US","DHS records on request","VA BIRLS, ENFORCE requests"],
  [52,2,"CBP Public Data Portal","https://www.cbp.gov","open","US","Border encounter data","Remains transfer, border flow"],
  [53,2,"CBP Nationwide Encounters","https://www.cbp.gov","open","US","Monthly encounter statistics","Mexico-US border context"],
  [54,2,"USCIS Immigration and Citizenship Data","https://www.uscis.gov","open","US","Adjudication stats","Naturalization denial counts"],
  [55,2,"USCIS Military Naturalization Excel","https://www.uscis.gov/military","open","US","800,000+ military naturalizations","Non-citizen service verification"],
  [56,2,"USCIS Refugee Processing Data","https://www.uscis.gov","open","US","Refugee stats","Foreign-national context"],
  [57,2,"USCIS FOIA Portal","https://www.uscis.gov/records","foia","US","A-files, N-400 records","Individual naturalization records"],
  [58,2,"EOIR Immigration Court Statistics","https://www.justice.gov/eoir","open","US","Case outcomes, completion rates","Deportation proceeding analysis"],
  [59,2,"EOIR Case Status Online","https://acis.eoir.justice.gov","open","US","Individual case status","Veteran proceeding tracking"],
  [60,2,"DOJ PACER Federal Court Records","https://pacer.uscourts.gov","foia","US","Federal court filings","Immigration court cases"],
  [61,2,"FOIA.gov Federal Request Portal","https://www.foia.gov","key","US","Cross-agency FOIA tracking","All three overdue requests"],
  [62,2,"DHS S&T Research Database","https://www.dhs.gov","open","US","DHS-funded research","Veteran deportation policy studies"],
  [63,2,"State Department Passport Records","https://ppt.state.gov","foia","US","Passport/travel records","KIA repatriation documentation"],
  [64,2,"State Department FOIA — Cables","https://foia.state.gov","foia","US","Diplomatic cables, reports","US Embassy Mexico City Vietnam cables"],
  [65,2,"State Department Foreign Affairs Manual","https://fam.state.gov","open","US","Policy guidance docs","Consular nationality rules"],
  [66,2,"USCIS Policy Manual","https://www.uscis.gov/policy-manual","open","US","Immigration policy text","INA §328, §329, §329A citations"],
  [67,2,"DOJ Immigration Enforcement Statistics","https://www.justice.gov","open","US","Removal stats","Veteran removals by charge"],
  [68,2,"National Security Archive (Immigration)","https://nsarchive.gwu.edu","open","US","Declassified immigration docs","1996 IIRIRA legislative history"],
  [69,2,"DHS Office for Civil Rights","https://www.dhs.gov","open","US","Civil rights reports","Veteran civil rights violations"],
  [70,2,"CBP One App Data","https://www.cbp.gov/cbpone","open","US","Parole/entry data","Cross-border veteran movement"],
  [71,2,"DHS Blue Campaign","https://www.dhs.gov","open","US","Trafficking data","Vulnerable veteran populations"],
  [72,2,"EOIR Policy Priorities","https://www.justice.gov/eoir","open","US","Immigration court policy","Veteran deportation precedent"],
  [73,2,"INS Historical Records (pre-DHS)","https://catalog.archives.gov","open","US","Pre-2003 immigration records","Vietnam-era non-citizen status"],
  [74,2,"NARA RG85 (Immigration and Naturalization)","https://catalog.archives.gov/id/605019","open","US","INS case files","Alien registration, A-files"],
  [75,2,"NARA RG566 (DHS/INS)","https://catalog.archives.gov","open","US","Post-2003 DHS records","Modern removal records"],
  [76,2,"TRAC Immigration Data Center","https://trac.syr.edu","open","US","Immigration court analytics","Veteran removal trends"],
  [77,2,"Migration Policy Institute Data Hub","https://www.migrationpolicy.org","open","US","Immigration statistics","Non-citizen veteran estimates"],
  [78,2,"DHS Privacy Impact Assessments","https://www.dhs.gov","open","US","ENFORCE, IDENT system docs","ENFORCE database architecture"],
  [79,2,"IDENT Biometric Database Docs","https://www.dhs.gov","open","US","Biometric system docs","ICE tracking methodology"],
  [80,2,"DOJ National Security Division","https://www.justice.gov/nsd","foia","US","National security removals","Non-citizen veteran national security cases"],
  [81,2,"CBP Seized Assets Database","https://www.cbp.gov","open","US","Border seizure data","Veteran reintegration barriers"],
  [82,2,"Customs and Border Patrol Historical Archives","https://www.cbp.gov","open","US","CBP institutional history","Vietnam-era border policy"],
  [83,2,"Office of Immigration Statistics (OIS) Data","https://www.dhs.gov","open","US","Annual flow statistics","Deportation volume baseline"],
  // SECTION 3 — US Federal: Veterans Affairs (84-105)
  [84,3,"VA BIRLS Beneficiary Identification Records","https://www.va.gov/foia","foia","US","Foreign-born veteran benefits","CRITICAL: Overdue FOIA"],
  [85,3,"VA NCVAS National Center for Veterans Analysis","https://www.va.gov/vetdata/","open","US","Veteran population stats","Non-citizen veteran estimates"],
  [86,3,"VA Open Data Portal","https://www.data.va.gov","open","US","VA datasets","Veteran demographics"],
  [87,3,"VA NPCD National Patient Care Database","https://www.va.gov/health","foia","US","Healthcare utilization","PTSD/MST among deported vets"],
  [88,3,"VetPop2020 Veteran Population Projections","https://www.va.gov/vetdata","open","US","Veteran population projections","Foreign-born baseline"],
  [89,3,"VA National Cemetery Administration","https://www.cem.va.gov","open","US","Burial records","Vietnam KIA burial verification"],
  [90,3,"VA Gravesite Locator","https://gravelocator.cem.va.gov","open","US","Individual burial records","KIA burial confirmation"],
  [91,3,"VA Research on Veterans with Disabilities","https://www.research.va.gov","open","US","Health research publications","PTSD-deportation nexus"],
  [92,3,"VA Adaptive Sports Database","https://www.va.gov/adaptive-sports","open","US","Program data","Veteran services access"],
  [93,3,"VA Accountability and Whistleblower Protection Office","https://www.va.gov/accountability","open","US","Accountability reports","DHS Noem contradiction evidence"],
  [94,3,"VA Inspector General Reports","https://www.va.gov/oig","open","US","OIG investigations","Veteran benefit denials"],
  [95,3,"Vietnam Veterans of America Research","https://vva.org/research/","open","US","Policy papers","Vietnam-era veteran advocacy"],
  [96,3,"VA Caregiver Support Program Data","https://www.va.gov","open","US","Caregiver statistics","Deported veteran family impact"],
  [97,3,"VA Fast Letter Databases","https://www.knowva.ebenefits.va.gov","open","US","Policy guidance","Non-citizen veteran eligibility"],
  [98,3,"VA CHAMPVA (foreign-born dependents)","https://www.va.gov","open","US","Dependent healthcare","Deportee family benefits"],
  [99,3,"NCA Burial Eligibility Data","https://www.cem.va.gov","open","US","Eligibility rules","Non-citizen KIA burial rights"],
  [100,3,"VHA Survey of Veteran Enrollees","https://www.va.gov","open","US","Healthcare enrollment","Non-citizen enrollment data"],
  [101,3,"VA Transition Assistance Program","https://www.benefits.va.gov/tap/","open","US","Transition data","Non-citizen discharge patterns"],
  [102,3,"VA Benefits Administration Data","https://www.benefits.va.gov","open","US","Claims/compensation stats","Denied benefits to deported vets"],
  [103,3,"American Battle Monuments Commission","https://www.abmc.gov","open","US","Overseas burial records","Vietnam KIA overseas burial"],
  [104,3,"VA Foreign Medical Program","https://www.va.gov","open","US","International healthcare","Mexico-side deported veteran healthcare"],
  [105,3,"Veterans Crisis Line Data","https://www.veteranscrisisline.net","open","US","Crisis intervention stats","Mental health of deported vets"],
  // SECTION 4 — US Intelligence: Declassified (106-123)
  [106,4,"CIA CREST (Declassified Records)","https://www.cia.gov/readingroom/crest","open","US","Declassified CIA documents","Chicano Moratorium CIA reports"],
  [107,4,"CIA Electronic Reading Room","https://www.cia.gov/readingroom/","open","US","FOIA-released CIA docs","Vietnam-era intelligence"],
  [108,4,"NSA Historical Records (Declassified)","https://www.nsa.gov","open","US","NSA declassified docs","Vietnam SIGINT context"],
  [109,4,"DNI ODNI Transparency Portal","https://www.dni.gov","open","US","Intelligence community releases","Domestic surveillance, Moratorium"],
  [110,4,"FBI Vault (Declassified Records)","https://vault.fbi.gov","open","US","FBI COINTELPRO, case files","Chicano movement surveillance"],
  [111,4,"FBI Records Vault — Chicano Moratorium","https://vault.fbi.gov/chicano-moratorium","open","US","Moratorium surveillance files","August 29, 1970 documentation"],
  [112,4,"DIA Defense Intelligence Agency","https://www.dia.mil/FOIA","open","US","DIA declassified","Vietnam intelligence assessments"],
  [113,4,"National Security Archive — GWU","https://nsarchive.gwu.edu","open","US","Tens of thousands declassified docs","Pentagon Papers, Vietnamization"],
  [114,4,"NSA Archive — Vietnam War","https://nsarchive.gwu.edu/collection/vietnam-war","open","US","Vietnam declassified collection","MACV reporting, casualties"],
  [115,4,"State Department FOIA — Cables","https://foia.state.gov","foia","US","Diplomatic cables","Embassy Mexico City Vietnam reports"],
  [116,4,"Senate Intelligence Committee Reports","https://www.intelligence.senate.gov","open","US","Committee reports","Intelligence oversight"],
  [117,4,"House Permanent Select Committee on Intelligence","https://intelligence.house.gov","open","US","HPSCI reports","Intelligence community oversight"],
  [118,4,"Church Committee Records (NARA)","https://catalog.archives.gov","open","US","1975 intelligence investigations","COINTELPRO, domestic surveillance"],
  [119,4,"COINTELPRO Documents (FBI Vault)","https://vault.fbi.gov/cointel-pro","open","US","FBI domestic surveillance","Chicano movement, Moratorium"],
  [120,4,"HUAC Records (NARA)","https://catalog.archives.gov","open","US","Un-American Activities records","Chicano political surveillance"],
  [121,4,"Office of the DNI Reports","https://www.dni.gov","open","US","ODNI annual reports","Intelligence community context"],
  [122,4,"Declassified Documents Reference System","https://www.gale.com","sub","US","Declassified government docs","Vietnam policy archives"],
  [123,4,"Digital National Security Archive","https://proquest.libguides.com/dnsa","sub","US","Declassified collections","Vietnam, Chicano surveillance"],
  // SECTION 5 — US Federal: Legislative & Regulatory (124-151)
  [124,5,"Congress.gov API","https://api.congress.gov","key","US","Legislation, hearings, votes","CHC briefing, NDAA, IIRIRA"],
  [125,5,"GovInfo API","https://www.govinfo.gov","key","US","Federal publications","Congressional Record, GAO, CRS"],
  [126,5,"Congressional Record (Full Text)","https://www.congress.gov","key","US","Floor debates text","Vietnam-era military debate"],
  [127,5,"CRS Congressional Research Service","https://crsreports.congress.gov","open","US","Policy research reports","R48163 (Foreign Nationals in Military)"],
  [128,5,"GAO Government Accountability Office","https://www.gao.gov","open","US","GAO reports/audits","GAO-19-416 (92 deported vets)"],
  [129,5,"Federal Register API","https://www.federalregister.gov","open","US","Regulatory text","Immigration rule changes"],
  [130,5,"USAspending API","https://api.usaspending.gov","open","US","Federal spending data","VA/DoD program budgets"],
  [131,5,"Data.gov Catalog API","https://catalog.data.gov","open","US","Federal dataset catalog","Discovery of hidden datasets"],
  [132,5,"api.data.gov Gateway","https://api.data.gov","open","US","Multi-agency API gateway","Access to agency APIs"],
  [133,5,"House Veterans Affairs Committee","https://veterans.house.gov","open","US","Committee hearings/reports","Veteran deportation hearings"],
  [134,5,"Senate Armed Services Committee","https://www.armed-services.senate.gov","open","US","SASC hearings","Military personnel policy"],
  [135,5,"Senate Judiciary Committee","https://www.judiciary.senate.gov","open","US","Immigration hearings","IIRIRA, deportation reform"],
  [136,5,"Congressional Hispanic Caucus","https://chc.house.gov","open","US","CHC statements, reports","Primary CHC briefing target"],
  [137,5,"House Appropriations Committee","https://appropriations.house.gov","open","US","VA/DoD funding","Veteran program funding"],
  [138,5,"Senate Veterans Affairs Committee","https://www.veterans.senate.gov","open","US","SVAC hearings","Non-citizen veteran legislation"],
  [139,5,"INA Immigration and Nationality Act","https://uscode.house.gov","open","US","Statutory text","§328, §329, §329A, §240A"],
  [140,5,"50 U.S.C. §3802 Military Selective Service Act","https://uscode.house.gov","open","US","Draft law text","Non-citizen induction authority"],
  [141,5,"IIRIRA (Pub. L. 104-208)","https://www.congress.gov","open","US","1996 immigration law","Retroactive deportation provisions"],
  [142,5,"Pub. L. 101-249 (INA §329A)","https://www.congress.gov","open","US","Posthumous citizenship act","Not retroactive to Vietnam"],
  [143,5,"Philippine Enlistment Program Records","https://catalog.archives.gov","open","US","Filipino Navy enlistees","PEP confound isolation"],
  [144,5,"Project 100,000 Records","https://catalog.archives.gov","open","US","McNamara's 100,000 records","Low-aptitude draftee context"],
  [145,5,"Selective Service Annual Report (NARA)","https://catalog.archives.gov","open","US","Draft system reports","Non-citizen draft percentages"],
  [146,5,"Office of Legal Counsel Opinions (DOJ)","https://www.justice.gov/olc","open","US","DOJ legal opinions","Non-citizen military eligibility"],
  [147,5,"OMBWatch Budget Database","https://datalab.usaspending.gov","open","US","Federal budget data","Defense/VA appropriations"],
  [148,5,"White House EO Database","https://www.federalregister.gov","open","US","Executive orders","Military service EOs"],
  [149,5,"National Security Presidential Directives","https://fas.org/irp/offdocs/nspd/","open","US","NSC directives","Vietnam-era policy"],
  [150,5,"Legislative Information System (LIS)","https://www.congress.gov","key","US","Full legislative history","DACA, DREAM Act, veteran bills"],
  [151,5,"OMB Circular A-110 / Statistical Directive 15","https://www.whitehouse.gov","open","US","Race classification standards","Pre-1977 DCAS coding context"],
  // SECTION 6 — US Federal: Demographics & Census (152-175)
  [152,6,"Census Bureau Data API","https://api.census.gov","key","US","All census datasets","BISG geographic priors"],
  [153,6,"Census 2010 Surname File","https://www.census.gov","open","US","162,253 surnames","BISG surname probabilities"],
  [154,6,"Census 2000 Surname File","https://www.census.gov","open","US","Historical surname data","Vietnam-era BISG baseline"],
  [155,6,"American Community Survey (ACS) 5-Year","https://data.census.gov","key","US","State demographics","Hispanic % by state for BISG"],
  [156,6,"Decennial Census 1970","https://data.census.gov","key","US","1970 population","Vietnam-era Hispanic population"],
  [157,6,"Decennial Census 1980","https://data.census.gov","key","US","1980 population","Post-war Hispanic population"],
  [158,6,"Census TIGER/Line Geographic Data","https://www.census.gov","open","US","Geographic boundaries","Home-of-record geolocation"],
  [159,6,"Census International Data Base","https://www.census.gov","open","US","International population","Mexico population baseline"],
  [160,6,"Census Microdata (IPUMS)","https://usa.ipums.org","key","US","Individual-level census","Vietnam-era Hispanic demographics"],
  [161,6,"IPUMS CPS Current Population Survey","https://cps.ipums.org","key","US","Labor/demographics panel","Non-citizen workforce data"],
  [162,6,"Census Race and Hispanic Origin Data","https://www.census.gov","key","US","Race classification data","BISG methodology baseline"],
  [163,6,"Census Surname Probability Model (BISG)","https://www.rand.org","open","US","BISG implementation","Direct BISG scoring tool"],
  [164,6,"RAND BISG R Package (wru)","https://cran.r-project.org","open","US","R/wru package","Computational BISG inference"],
  [165,6,"BLS Bureau of Labor Statistics","https://www.bls.gov","key","US","Labor market data","Veteran employment post-service"],
  [166,6,"BLS LAUS Local Area Unemployment","https://www.bls.gov/lau/","key","US","County-level unemployment","Border region economic context"],
  [167,6,"CDC WONDER Mortality Data","https://wonder.cdc.gov","open","US","Mortality statistics","Vietnam-era death rates"],
  [168,6,"CDC National Death Index","https://www.cdc.gov","manual","US","Death records","KIA cross-reference"],
  [169,6,"Social Security Death Master File","https://www.ssdmf.com","foia","US","Death records","KIA death verification"],
  [170,6,"SSA Public Death Records","https://www.ssa.gov","open","US","Death benefit files","Casualty verification"],
  [171,6,"IRS Statistics of Income (SOI)","https://www.irs.gov","open","US","Tax/income data","Economic impact of deportation"],
  [172,6,"Federal Reserve Economic Data (FRED)","https://fred.stlouisfed.org","key","US","Economic indicators","Remittance, economic context"],
  [173,6,"IPUMS NHGIS Historical GIS","https://www.nhgis.org","key","US","Historical geographic data","Vietnam-era Hispanic population maps"],
  [174,6,"National Center for Education Statistics","https://nces.ed.gov","open","US","Education data","Draft deferment by education level"],
  [175,6,"Pew Research Center Datasets","https://www.pewresearch.org","open","US","Survey/demographic data","Hispanic veteran attitudes"],
  // SECTION 7 — US Federal: Courts & Legal (176-195)
  [176,7,"PACER Federal Court Electronic Records","https://pacer.uscourts.gov","foia","US","Federal court filings","Deportation proceeding records"],
  [177,7,"RECAP Archive (Free PACER)","https://www.courtlistener.com/recap/","open","US","PACER documents (free)","Veteran deportation cases"],
  [178,7,"CourtListener Federal Opinions","https://www.courtlistener.com","open","US","Court opinions full text","Non-citizen veteran case law"],
  [179,7,"BIA Board of Immigration Appeals Decisions","https://www.justice.gov/eoir","open","US","Immigration appeal decisions","Veteran removal appeals"],
  [180,7,"EOIR Case Status Query","https://acis.eoir.justice.gov","open","US","Individual case status","Real-time case monitoring"],
  [181,7,"Supreme Court Cases (Oyez)","https://www.oyez.org","open","US","SCOTUS decisions/arguments","Immigration citizenship precedent"],
  [182,7,"Ninth Circuit Immigration Decisions","https://cdn.ca9.uscourts.gov","open","US","9th Circuit opinions","CA/AZ border veteran cases"],
  [183,7,"National Immigrant Justice Center","https://immigrantjustice.org","open","US","Impact litigation docs","Veteran deportation litigation"],
  [184,7,"Harvard Caselaw Access Project","https://case.law","open","US","6.7M US court cases","Historical immigration cases"],
  [185,7,"Cornell LII US Code","https://www.law.cornell.edu","open","US","US Code full text","INA, IIRIRA, 50 USC"],
  [186,7,"DOJ Civil Rights Division","https://www.justice.gov/crt","open","US","Civil rights enforcement","Veteran rights violations"],
  [187,7,"ACLU Know Your Rights","https://www.aclu.org","open","US","Rights documentation","Veteran legal rights"],
  [188,7,"National Immigration Law Center","https://www.nilc.org","open","US","Immigration law resources","DACA, veteran protection bills"],
  [189,7,"American Immigration Lawyers Association (AILA)","https://www.aila.org","open","US","Immigration case resources","Legal precedent research"],
  [190,7,"Immigrant Legal Resource Center (ILRC)","https://www.ilrc.org","open","US","Legal guides, practice advisories","Military immigration legal practice"],
  [191,7,"National Security Law Reports (NDAA)","https://www.lawfaremedia.org","open","US","National security law analysis","Non-citizen military service law"],
  [192,7,"BVA Board of Veterans Appeals Decisions","https://www.bva.va.gov","open","US","VA appeal decisions","Non-citizen veteran appeals"],
  [193,7,"US Court of Appeals for Veterans Claims","https://www.uscourts.cavc.gov","open","US","Veterans court decisions","Deported veteran benefits appeals"],
  [194,7,"Law360 Immigration Database","https://www.law360.com","sub","US","Case coverage","Veteran deportation litigation"],
  [195,7,"Westlaw Immigration Cases","https://legal.thomsonreuters.com","sub","US","Full case law","Comprehensive legal research"],
  // SECTION 8 — US Federal: Health & Social (196-211)
  [196,8,"SAMHSA NSDUH Survey","https://www.samhsa.gov","open","US","Substance use/mental health","PTSD-deportation nexus"],
  [197,8,"VA PTSD Research Database","https://www.ptsd.va.gov","open","US","PTSD clinical research","Combat PTSD, criminal charges"],
  [198,8,"National Violent Death Reporting System","https://www.cdc.gov","open","US","Violent death records","Veteran suicide/homicide"],
  [199,8,"NCHS National Health Interview Survey","https://www.cdc.gov/nchs/nhis/","open","US","Health demographics","Non-citizen veteran health"],
  [200,8,"HRSA Health Resources and Services","https://data.hrsa.gov","open","US","Healthcare access","Border region healthcare access"],
  [201,8,"Mental Health America State Rankings","https://mhanational.org","open","US","Mental health access","Veteran mental health access"],
  [202,8,"National Alliance on Mental Illness (NAMI)","https://nami.org","open","US","Mental health data","PTSD in deportation context"],
  [203,8,"CDC Veterans Health Data","https://www.cdc.gov","open","US","Veteran health statistics","Combat-related health issues"],
  [204,8,"NIH PubMed (PTSD + deportation)","https://pubmed.ncbi.nlm.nih.gov","open","US","Biomedical literature","Academic evidence base"],
  [205,8,"HHS Office of Minority Health","https://www.minorityhealth.hhs.gov","open","US","Minority health data","Hispanic veteran health disparities"],
  [206,8,"ACF Administration for Children and Families","https://www.acf.hhs.gov","open","US","Family/child welfare","Veteran family separation impact"],
  [207,8,"DHHS Refugee Medical Assistance","https://www.acf.hhs.gov/orr","open","US","Refugee health programs","Deported veteran healthcare access"],
  [208,8,"NREPP Evidenced-Based Programs","https://www.samhsa.gov","open","US","Treatment programs","PTSD treatment resources"],
  [209,8,"AHRQ Healthcare Quality Data","https://www.ahrq.gov","open","US","Healthcare quality","VA healthcare quality disparities"],
  [210,8,"Children's Defense Fund","https://www.childrensdefense.org","open","US","Child welfare data","Family impact of deportation"],
  [211,8,"Urban Institute Social Safety Net","https://www.urban.org","open","US","Social program data","Deported veteran program access"],
  // SECTION 9 — US State & Local (212-253) — abbreviated for key entries
  [212,9,"California Open Data Portal","https://data.ca.gov","open","US","CA state datasets","Largest Hispanic veteran state"],
  [213,9,"CA Dept. of Veterans Affairs","https://www.calvet.ca.gov","open","US","CA veteran services","Non-citizen veteran programs"],
  [214,9,"CA Courts — Immigration Cases","https://www.courts.ca.gov","open","US","State court records","CA deportation proceedings"],
  [215,9,"LA County Open Data","https://data.lacounty.gov","open","US","LA County datasets","East LA Moratorium context"],
  [216,9,"Los Angeles Times Digital Archive","https://www.latimes.com","open","US","News archive","Chicano Moratorium coverage"],
  [217,9,"Texas Open Data Portal","https://data.texas.gov","open","US","Texas state data","TX Hispanic military casualties"],
  [218,9,"Texas Veterans Commission","https://www.tvc.texas.gov","open","US","TX veteran services","Non-citizen veteran support"],
  [219,9,"Arizona State Library Archives","https://azlibrary.gov","manual","US","AZ historical records","Borderlands documentation"],
  [220,9,"Arizona Veterans Services Division","https://dvs.az.gov","open","US","AZ veteran data","Non-citizen veteran benefits"],
  [221,9,"New Mexico State Records Center","https://www.nmcpr.state.nm.us","open","US","NM historical records","NM Hispanic casualty context"],
  [222,9,"New Mexico Veterans Services Dept.","https://www.nmd.state.nm.us","open","US","NM veteran services","Hispanic veteran services"],
  [223,9,"Illinois Dept. of Veterans Affairs","https://www.illinois.gov/sites/veterans/","open","US","IL veteran data","Chicago Hispanic veteran community"],
  [224,9,"Chicago City Data Portal","https://data.cityofchicago.org","open","US","Chicago datasets","Pilsen/Little Village casualty context"],
  [225,9,"Colorado Veterans Affairs","https://www.colorado.gov/veterans","open","US","CO veteran data","CO Hispanic veteran programs"],
  [226,9,"San Diego County Open Data","https://data.sandiegocounty.gov","open","US","SD County datasets","Tijuana border context"],
  [227,9,"California State Archives","https://www.sos.ca.gov/archives","manual","US","Historical CA records","Chicano Movement archives"],
  [228,9,"Cal State LA Chicano Studies Library","https://www.calstatela.edu/library","manual","US","Chicano studies archives","Moratorium, casualty research"],
  [229,9,"UCLA Chicano Studies Research Center","https://www.chicano.ucla.edu","open","US","Chicano studies publications","Foundational casualty research"],
  [230,9,"USC Digital Library","https://digitallibrary.usc.edu","open","US","USC digital collections","Vietnam-era CA documents"],
  [231,9,"Stanford Libraries Special Collections","https://library.stanford.edu","manual","US","Stanford archives","Chicano movement papers"],
  [232,9,"Berkeley Bancroft Library","https://bancroft.berkeley.edu","manual","US","Oral history, Western Americana","Chicano movement oral history"],
  [233,9,"California Digital Library","https://cdlib.org","open","US","Digitized CA collections","Border region archives"],
  [234,9,"UCSD Mandeville Special Collections","https://library.ucsd.edu","manual","US","San Diego border archives","Tijuana, deportation records"],
  [235,9,"El Paso County Open Data","https://data.elpasotx.gov","open","US","El Paso datasets","Ciudad Juárez connection"],
  [236,9,"Tucson City Open Data","https://www.tucsonaz.gov/data","open","US","Tucson datasets","AZ border veteran context"],
  [237,9,"State of Texas Legislative Archive","https://www.lrl.texas.gov","open","US","TX legislative records","TX veteran protection bills"],
  [238,9,"Arizona Digital Collections","https://repository.asu.edu","open","US","ASU digital archive","Borderlands, Chicano history"],
  [239,9,"Nevada Veterans Services","https://veterans.nv.gov","open","US","NV veteran data","NV Hispanic veteran community"],
  [240,9,"Colorado State Archives","https://www.sos.state.co.us/archives","open","US","CO historical records","CO Hispanic military history"],
  [241,9,"San Ysidro Border Crossing Data","https://www.bts.gov","open","US","Border crossing stats","Deportee return/crossing data"],
  [242,9,"Bureau of Transportation Statistics Border Data","https://www.bts.gov","open","US","Border flow data","Cross-border veteran tracking"],
  [243,9,"California Center for Border Economic Studies","https://www.sandag.org","open","US","Border economic data","Deported veteran economic impact"],
  [244,9,"SANDAG San Diego Border Data","https://www.sandag.org","open","US","Regional border data","Tijuana shelter population"],
  [245,9,"LA County Dept. of Veterans Services","https://dvs.lacounty.gov","open","US","LA veteran services","East LA deportation cases"],
  [246,9,"Sacramento State Center for California Studies","https://www.csus.edu","manual","US","California history","Vietnam-era CA documents"],
  [247,9,"Arizona Memory Project","https://azmemory.azlibrary.gov","open","US","AZ digitized history","AZ Vietnam-era records"],
  [248,9,"Portal to Texas History (UNT)","https://texashistory.unt.edu","open","US","Texas historical documents","TX Vietnamese-American, Hispanic"],
  [249,9,"New Mexico Digital Collections","https://econtent.unm.edu","open","US","NM digitized history","NM Hispanic military history"],
  [250,9,"Nevada Digital Collections (UNLV)","https://digitalcollections.library.unlv.edu","open","US","NV digital history","Hispanic Nevada veteran records"],
  [251,9,"Colorado Virtual Library","https://www.coloradovirtuallibrary.org","open","US","CO digital collections","CO Hispanic military context"],
  [252,9,"Los Angeles Public Library Digital","https://tessa.lapl.org","open","US","LA historical photos/docs","East LA Moratorium imagery"],
  [253,9,"San Diego Public Library Digital","https://www.sandiegolibrary.org","open","US","SD digitized history","Tijuana cross-border history"],
  // SECTION 10 — Mexico Federal Government (254-291)
  [254,10,"INM Statistical Yearbook","https://www.gob.mx/inm","open","MX","50K-100K+ annual US deportations","Mexican side deportation data"],
  [255,10,"INM INAI Solicitud (Mexico FOIA)","https://www.gob.mx/inm","foia","MX","Specific deportation microdata","CRITICAL: Overdue FOIA"],
  [256,10,"INAI Plataforma Nacional de Transparencia","https://consultapublicamx.plataformadetransparencia.org.mx","foia","MX","All Mexico FOIA requests","Gateway for all MX government FOIA"],
  [257,10,"INEGI Indicators API","https://www.inegi.org.mx/servicios/api_indicadores.html","key","MX","Mexico statistical indicators","Demographic baseline Mexico-side"],
  [258,10,"INEGI Census 2020","https://www.inegi.org.mx","open","MX","Mexico population data","US-born in Mexico populations"],
  [259,10,"INEGI ENOE Employment Survey","https://www.inegi.org.mx","open","MX","Labor force data","Deported veteran employment"],
  [260,10,"INEGI ENADIS Discrimination Survey","https://www.inegi.org.mx","open","MX","Discrimination data","Veterans experience in Mexico"],
  [261,10,"SRE Secretaría de Relaciones Exteriores","https://www.gob.mx/sre","open","MX","Bilateral agreements","US-Mexico veteran support programs"],
  [262,10,"SRE Programa de Repatriación","https://www.gob.mx/sre","open","MX","Repatriation program data","Deportee reception programs"],
  [263,10,"RENAPO National Population Registry","https://www.gob.mx/segob","foia","MX","Population registry","Identity verification Mexico-side"],
  [264,10,"INE Instituto Nacional Electoral","https://www.ine.mx","open","MX","Electoral/demographic data","Voter ID, demographic records"],
  [265,10,"INE Cartografía Electoral","https://cartografia.ine.mx","open","MX","Electoral maps","Geographic demographic data"],
  [266,10,"datos.gob.mx Open Data Portal","https://www.datos.gob.mx","open","MX","Mexico federal datasets","Discovery of MX government data"],
  [267,10,"PNT Plataforma Nacional de Transparencia","https://www.plataformadetransparencia.org.mx","open","MX","Government transparency records","All MX agency transparency"],
  [268,10,"PNT Datos Abiertos","https://www.plataformadetransparencia.org.mx","open","MX","Government open data","MX government datasets"],
  [269,10,"AGN Archivo General de la Nación","https://www.gob.mx/agn","manual","MX","Mexico national archives","Naturalization records, military history"],
  [270,10,"AGN Repositorio Documental Digital","https://repositorio.agn.gob.mx","open","MX","Digitized national archives","Historical Mexican military records"],
  [271,10,"AGN Guía General","https://guiageneral.agn.gob.mx","open","MX","Finding aids for collections","Research pathway to archives"],
  [272,10,"AGN SIGBIC Library System","https://biblioteca.agn.gob.mx","open","MX","AGN library catalog","Bibliography, historical records"],
  [273,10,"CNDH Comisión Nacional de Derechos Humanos","https://www.cndh.org.mx","open","MX","Human rights reports","Deported veteran rights violations"],
  [274,10,"CNDH Migrant Rights Portal","https://www.cndh.org.mx","open","MX","Migrant human rights data","Deported veteran protection"],
  [275,10,"CNDH Estancias Migratorias Report","https://www.cndh.org.mx","open","MX","Migrant detention report","Detention conditions review"],
  [276,10,"COMAR Comisión Mexicana de Ayuda a Refugiados","https://www.gob.mx/comar","open","MX","Refugee/asylum data","Veteran refugee status Mexico-side"],
  [277,10,"OMI Oficina para Personas Migrantes","https://omi.gob.mx","open","MX","Migrant shelter locations","Shelter network in Mexico"],
  [278,10,"SEDENA Secretaría de la Defensa Nacional","https://www.gob.mx/sedena","foia","MX","Mexico military records","Mexico military service records"],
  [279,10,"SEMAR Secretaría de Marina","https://www.gob.mx/semar","foia","MX","Mexico navy records","Mexico naval service records"],
  [280,10,"SSN Servicio de Salud","https://www.gob.mx/salud","open","MX","Health data Mexico","Deported veteran health access"],
  [281,10,"Diario Oficial de la Federación (DOF)","https://www.dof.gob.mx","open","MX","Mexican federal register","Immigration law text Mexico"],
  [282,10,"SAT Mexico Tax Authority","https://www.sat.gob.mx","open","MX","Tax records","Deported veteran economic tracking"],
  [283,10,"Banxico Banco de México","https://www.banxico.org.mx","key","MX","Financial data","Remittances from deported vets"],
  [284,10,"STPS Secretaría del Trabajo","https://www.gob.mx/stps","open","MX","Labor data Mexico","Veteran employment Mexico-side"],
  [285,10,"CONAPO Consejo Nacional de Población","https://www.gob.mx/conapo","open","MX","Mexico population projections","US-born return migration data"],
  [286,10,"Subsecretaría de Migración","https://www.gob.mx/inm","open","MX","Migration policy","Deportee reception policy"],
  [287,10,"IMSS Instituto Mexicano del Seguro Social","https://www.imss.gob.mx","open","MX","Social security Mexico","Deported veteran healthcare"],
  [288,10,"CDI / INPI Indigenous Peoples Institute","https://www.gob.mx/inpi","open","MX","Indigenous population data","Indigenous Mexican veteran tracking"],
  [289,10,"SEGOB Secretaría de Gobernación","https://www.gob.mx/segob","foia","MX","Interior ministry records","Immigration policy decisions"],
  [290,10,"Secretaría de Bienestar","https://www.gob.mx/bienestar","open","MX","Social welfare data","Deported veteran welfare access"],
  [291,10,"CONEVAL Poverty Evaluation Council","https://www.coneval.org.mx","open","MX","Poverty/welfare data","Deported veteran poverty rates"],
  // SECTION 11 — Mexico State & Local (292-315)
  [292,11,"Baja California Open Data","https://gobiernoabierto.bajacalifornia.gob.mx","open","MX","BC state datasets","Tijuana shelter/veteran context"],
  [293,11,"Baja California Budget Data","https://www.bajacalifornia.gob.mx","open","MX","BC financial data","Shelter funding context"],
  [294,11,"Baja California State Portal","https://www.bajacalifornia.gob.mx","open","MX","BC government info","State policy for deportees"],
  [295,11,"Tijuana Municipal Portal","https://www.tijuana.gob.mx","open","MX","Tijuana city data","Casa de Apoyo municipal context"],
  [296,11,"Tijuana Transparency Portal","https://transparencia.tijuana.gob.mx","open","MX","Tijuana government records","Local shelter documentation"],
  [297,11,"Tijuana Migrant/Refugee Guide","https://www.tijuana.gob.mx","open","MX","Migrant services guide","Shelter services directory"],
  [298,11,"Mexicali Transparency Portal","https://www.mexicali.gob.mx","open","MX","Mexicali records","Border city veteran data"],
  [299,11,"Sonora Transparency Portal","https://transparencia.sonora.gob.mx","open","MX","Sonora state records","Sonora deportee data"],
  [300,11,"Sonora State Open Data","https://www.sonora.gob.mx","open","MX","Sonora datasets","Sonora border context"],
  [301,11,"Chihuahua State Government","https://www.chihuahua.gob.mx","open","MX","Chihuahua data","Ciudad Juárez veteran shelter"],
  [302,11,"Chihuahua Transparency","https://www.chihuahua.gob.mx/transparencia","open","MX","Chihuahua records","Casa de Apoyo CJ context"],
  [303,11,"Nuevo León Open Government","https://www.nl.gob.mx","open","MX","NL state data","Monterrey deportee population"],
  [304,11,"Tamaulipas State Portal","https://www.tamaulipas.gob.mx","open","MX","Tamaulipas data","Matamoros/Reynosa border context"],
  [305,11,"Coahuila State Portal","https://www.coahuila.gob.mx","open","MX","Coahuila data","Piedras Negras / Eagle Pass border"],
  [306,11,"Jalisco Open Data","https://datos.jalisco.gob.mx","open","MX","Jalisco state datasets","Guadalajara deportee community"],
  [307,11,"Ciudad de Mexico (CDMX) Open Data","https://datos.cdmx.gob.mx","open","MX","Mexico City datasets","National deportee networks"],
  [308,11,"Oaxaca State Portal","https://www.oaxaca.gob.mx","open","MX","Oaxaca data","Indigenous Mexican veteran context"],
  [309,11,"Michoacán State Portal","https://michoacan.gob.mx","open","MX","Michoacán data","High-emigration state context"],
  [310,11,"Guanajuato Open Data","https://datos.guanajuato.gob.mx","open","MX","Guanajuato datasets","High-emigration state deportees"],
  [311,11,"Puebla State Portal","https://www.puebla.gob.mx","open","MX","Puebla data","Puebla diaspora military context"],
  [312,11,"Veracruz State Portal","https://www.veracruz.gob.mx","open","MX","Veracruz data","Gulf state veteran community"],
  [313,11,"Sinaloa State Portal","https://sinaloa.gob.mx","open","MX","Sinaloa data","Sinaloa veteran deportees"],
  [314,11,"Baja California Sur State Portal","https://www.bcs.gob.mx","open","MX","BCS data","Pacific coast deportee context"],
  [315,11,"AGN Colima Branch Records","https://repositorio.agn.gob.mx","open","MX","State archive branches","Regional military history"],
  // SECTION 12 — Mexico Academic (316-335)
  [316,12,"HNDM Hemeroteca Nacional Digital de México","https://hndm.iib.unam.mx","open","MX","1.1M+ digitized newspaper pages","Spanish-language press coverage"],
  [317,12,"Biblioteca Nacional de México","https://bnm.iib.unam.mx","open","MX","National library catalog","Historical Mexican documents"],
  [318,12,"UNAM Institutional Repository","https://repositorio.unam.mx","open","MX","UNAM academic output","Mexican military, immigration research"],
  [319,12,"UNAM DGBSDI Repository","https://ru.dgb.unam.mx","open","MX","UNAM research reports","Diaspora, migration scholarship"],
  [320,12,"Repositorio Nacional México (CONACYT)","https://repositorionacionalcti.mx","open","MX","All Mexican academic output","Comprehensive MX scholarship"],
  [321,12,"UABC Institutional Repository","https://repositorioinstitucional.uabc.mx","open","MX","Baja California scholarship","Border region research"],
  [322,12,"El Colegio de la Frontera Norte (COLEF)","https://colef.repositorioinstitucional.mx","open","MX","Border migration research","CRITICAL: border veteran studies"],
  [323,12,"COLEF Tesis / Theses","https://posgrado.colef.mx","open","MX","COLEF dissertations","Deportation, migration theses"],
  [324,12,"COLEF SUDIMER Database","https://www.colef.mx","manual","MX","Mexican diaspora data","US-Mexico migrant data"],
  [325,12,"Colegio de México (COLMEX)","https://www.colmex.mx","open","MX","COLMEX scholarship","Mexican political history"],
  [326,12,"CIESAS Anthropological Research","https://www.ciesas.edu.mx","open","MX","Anthropological research","Indigenous, migration research"],
  [327,12,"FLACSO México","https://www.flacso.edu.mx","open","MX","Social science research","Human rights, migration"],
  [328,12,"CIDE Research","https://www.cide.edu","open","MX","Policy research","Mexico immigration policy"],
  [329,12,"UAM Repositorio Institucional","https://repositorio.uam.mx","open","MX","UAM scholarship","Mexico social research"],
  [330,12,"UNISON Repository","https://www.unison.mx","open","MX","Sonora-focused theses","Sonora border, immigration"],
  [331,12,"IBERO Universidad Iberoamericana","https://repositorio.ibero.mx","open","MX","Jesuit university scholarship","Human rights, indigenous studies"],
  [332,12,"IPN Instituto Politécnico Nacional","https://www.repositoriodigital.ipn.mx","open","MX","Technical/social research","Mexico demographics"],
  [333,12,"UV Universidad Veracruzana Repository","https://www.uv.mx","open","MX","Gulf region scholarship","Veracruz diaspora studies"],
  [334,12,"UAG Universidad Autónoma de Guadalajara","https://www.uag.mx","manual","MX","Jalisco scholarship","Jalisco deportee community"],
  [335,12,"UDLAP Universidad de las Américas Puebla","https://repositorio.udlap.mx","open","MX","Puebla scholarship","Migration studies"],
  // SECTION 13 — US Academic (336-367)
  [336,13,"Harvard Dataverse","https://dataverse.harvard.edu","open","US","Research datasets","doi:10.7910/DVN/O80SKQ APSR data"],
  [337,13,"ICPSR Inter-university Consortium","https://www.icpsr.umich.edu","key","US","Social science datasets","Vietnam-era military datasets"],
  [338,13,"OpenICPSR","https://www.openicpsr.org","open","US","Open replication data","Vietnam casualty replication data"],
  [339,13,"ProQuest Dissertations & Theses","https://www.proquest.com","sub","US","Dissertations","Chicano military studies"],
  [340,13,"JSTOR Research Content","https://www.jstor.org","sub","US","Academic journals","Vietnam-era Chicano scholarship"],
  [341,13,"Project MUSE","https://muse.jhu.edu","sub","US","Academic journals","'I'm Not Gonna Die in This Damn Place'"],
  [342,13,"EBSCO Academic Search","https://www.ebsco.com","sub","US","Full journal access","BISG methodology literature"],
  [343,13,"eScholarship (UC System)","https://escholarship.org","open","US","UC open access scholarship","'The Few, The Proud, The Deported'"],
  [344,13,"PhilPapers Philosophy Research","https://philpapers.org","open","US","Philosophy/social research","Ethics of deportation research"],
  [345,13,"SSRN Social Science Research Network","https://www.ssrn.com","open","US","Preprint working papers","Immigration law preprints"],
  [346,13,"arXiv Preprint Server","https://arxiv.org","open","US","Science preprints","BISG methodology papers"],
  [347,13,"Semantic Scholar","https://www.semanticscholar.org","open","US","200M+ papers","Comprehensive literature search"],
  [348,13,"OpenAlex Open Scholarly Graph","https://openalex.org","open","US","250M+ scholarly works","Full citation graph"],
  [349,13,"Crossref Metadata API","https://api.crossref.org","open","US","145M+ DOI records","Citation metadata"],
  [350,13,"ORCID Researcher Profiles","https://orcid.org","open","US","Researcher identifiers","Contact Barreto, Durazo, González"],
  [351,13,"ROR Research Organization Registry","https://ror.org","open","US","Institution identifiers","USC, UCLA, UCSB affiliations"],
  [352,13,"DataCite Metadata","https://datacite.org","open","US","Dataset DOI metadata","Research data citations"],
  [353,13,"BASE Bielefeld Academic Search","https://www.base-search.net","open","INT","300M+ academic documents","Chicano studies metadata"],
  [354,13,"CORE Open Research","https://core.ac.uk","open","INT","230M+ open access papers","Full text research retrieval"],
  [355,13,"Unpaywall Open Access API","https://unpaywall.org","open","INT","OA version finder","Find free versions of papers"],
  [356,13,"ERIC Education Resources","https://eric.ed.gov","open","US","Education research","Chicano studies curriculum"],
  [357,13,"Ralph C. Guzmán Papers (UCLA)","https://oac.cdlib.org","manual","US","Guzmán personal papers","CRITICAL: Foundational 1969 study"],
  [358,13,"Matt Barreto UCLA Research","https://polisci.ucla.edu","manual","US","BISG methodology","Doctoral committee resource"],
  [359,13,"Alfredo González UCSB Research","https://www.soc.ucsb.edu","manual","US","Developing to Deport research","Scholarly alignment confirmed"],
  [360,13,"USC Price School of Public Policy Library","https://price.usc.edu","manual","US","Policy research","Doctoral research infrastructure"],
  [361,13,"UC Berkeley Bancroft Library Oral History","https://bancroft.berkeley.edu/ROHO/","manual","US","Oral history transcripts","Vietnam-era veteran oral histories"],
  [362,13,"UT Austin LLILAS Benson","https://www.lib.utexas.edu/benson","manual","US","Latin American collections","Mexico border scholarship"],
  [363,13,"University of Arizona Special Collections","https://www.library.arizona.edu","manual","US","Borderlands collections","AZ borderlands oral history"],
  [364,13,"Notre Dame Hesburgh Libraries","https://library.nd.edu","manual","US","Latino studies collections","Catholic, Chicano scholarship"],
  [365,13,"Michigan State University Digital Collections","https://lib.msu.edu","open","US","MSU digital archive","Deported veteran documentary"],
  [366,13,"Berkeley Law School","https://www.law.berkeley.edu","open","US","Human rights law reports","2025 deported veteran report"],
  [367,13,"George Mason University Law Blog","https://ilt.gmu.edu","open","US","Legal scholarship","Deported veteran legal analysis"],
  // SECTION 14 — Think Tanks (368-395)
  [368,14,"RAND Corporation","https://www.rand.org","open","US","Defense/policy research","Military demographics, Vietnam studies"],
  [369,14,"RAND BISG Tool (wru)","https://www.rand.org","open","US","BISG R package","Computational surname scoring"],
  [370,14,"Pew Research Center","https://www.pewresearch.org","open","US","Public opinion, demographics","Hispanic veteran attitudes"],
  [371,14,"Pew Datasets (Free Download)","https://www.pewresearch.org","open","US","Survey microdata","Immigration attitudes data"],
  [372,14,"Urban Institute","https://www.urban.org","open","US","Social policy research","Immigration enforcement data"],
  [373,14,"Brookings Institution","https://www.brookings.edu","open","US","Policy research","Hispanic veteran policy analysis"],
  [374,14,"Migration Policy Institute (MPI)","https://www.migrationpolicy.org","open","INT","Immigration policy/data","Non-citizen veteran estimates"],
  [375,14,"Center for American Progress","https://www.americanprogress.org","open","US","Progressive policy research","Deported veteran advocacy data"],
  [376,14,"Center for Immigration Studies (CIS)","https://cis.org","open","US","Immigration research","Deportation enforcement data"],
  [377,14,"American Immigration Council","https://www.americanimmigrationcouncil.org","open","US","Immigration legal research","Deported veteran database"],
  [378,14,"National Immigration Forum","https://immigrationforum.org","open","US","Immigration policy","DACA, veteran protection tracking"],
  [379,14,"Center for Migration Studies (CMS)","https://cmsny.org","open","US","Migration research","1996 IIRIRA impact analysis"],
  [380,14,"Cato Institute Immigration Research","https://www.cato.org","open","US","Libertarian policy research","Non-citizen service rights"],
  [381,14,"Heritage Foundation","https://www.heritage.org","open","US","Conservative policy","Military service immigration policy"],
  [382,14,"Wilson Center Mexico Institute","https://www.wilsoncenter.org","open","US","US-Mexico policy research","Cross-border veteran policy"],
  [383,14,"Inter-American Dialogue","https://www.thedialogue.org","open","INT","Latin America policy","US-Mexico veteran affairs"],
  [384,14,"Washington Office on Latin America (WOLA)","https://www.wola.org","open","INT","Human rights/Latin America","Deported veteran advocacy"],
  [385,14,"American Friends Service Committee","https://www.afsc.org","open","US","Quaker social justice","Deported veteran support"],
  [386,14,"Human Rights Watch","https://www.hrw.org","open","INT","Human rights reports","Veteran deportation documentation"],
  [387,14,"Amnesty International","https://www.amnesty.org","open","INT","Human rights data","Veteran deportation reports"],
  [388,14,"Council on Foreign Relations","https://www.cfr.org","open","US","Foreign policy research","US-Mexico bilateral, veterans"],
  [389,14,"InSight Crime","https://insightcrime.org","open","INT","Organized crime/Latin America","Deportation, criminal charge context"],
  [390,14,"International Crisis Group","https://www.crisisgroup.org","open","INT","Conflict data","US-Mexico border context"],
  [391,14,"Inter-American Commission on Human Rights","https://www.oas.org/en/iachr/","open","INT","IACHR reports","Veteran deportation human rights"],
  [392,14,"Fundar Centro de Análisis","https://fundar.org.mx","open","MX","Mexico civil society research","Mexico government transparency"],
  [393,14,"IMCO Instituto Mexicano para la Competitividad","https://imco.org.mx","open","MX","Mexico governance data","Mexico institutional research"],
  [394,14,"COMEXI Consejo Mexicano de Asuntos Internacionales","https://www.comexi.org.mx","open","MX","Mexico foreign policy","US-Mexico bilateral relations"],
  [395,14,"Woodrow Wilson Center","https://www.wilsoncenter.org","open","US","Scholarly policy research","Vietnam, Mexico, immigration"],
  // SECTION 15 — NGO, Shelters & Advocacy (396-425)
  [396,15,"Casa de Apoyo a Veteranos Deportados (Tijuana)","https://casademigrante.org","manual","MX","Veteran registry ~200 cases","CRITICAL: Primary Mexico-side registry"],
  [397,15,"Casa de Apoyo Ciudad Juárez","https://veteransforamericanideals.org","manual","MX","CJ veteran registry","Second Casa site"],
  [398,15,"Deported Veterans Support House (Tijuana)","https://deportedveteranssupporthouse.org","open","MX","~50-100 shelter cases","Named veteran cases"],
  [399,15,"Unified US Deported Veterans Resource Center","https://veteransforamericanideals.org","open","MX","100-200+ cases","Ciudad Juárez registry"],
  [400,15,"Vets Without Borders","https://vetswithoutborders.org","open","INT","100-300+ veteran registry","Cross-border veteran network"],
  [401,15,"ACLU Immigrants' Rights Project","https://www.aclu.org","manual","US","84+ deported veteran cases","Litigation records"],
  [402,15,"American Immigration Council Research","https://www.americanimmigrationcouncil.org","manual","US","Deported veteran database","Named case records"],
  [403,15,"National Immigration Project (NIP)","https://www.nipnlg.org","open","US","Immigration legal resources","Veteran deportation litigation"],
  [404,15,"Immigrant Defense Project","https://www.immigrantdefenseproject.org","open","US","Case documentation","IIRIRA impact cases"],
  [405,15,"Just Futures Law","https://justfutureslaw.org","open","US","Immigration legal research","Non-citizen veteran rights"],
  [406,15,"Veterans for American Ideals","https://www.veteransforamericanideals.org","open","US","Advocacy network","Deported veteran outreach"],
  [407,15,"Iraq and Afghanistan Veterans of America (IAVA)","https://iava.org","open","US","Veteran advocacy data","Non-citizen OIF/OEF vets"],
  [408,15,"VietNow National","https://vietnow.org","open","US","Vietnam veteran support","Vietnam vet advocacy"],
  [409,15,"Vietnam Veterans of America","https://vva.org","open","US","Policy, research","Vietnam-era casualty records"],
  [410,15,"National Veterans Legal Services Program","https://www.nvlsp.org","open","US","Legal aid data","Veteran benefits denied"],
  [411,15,"Swords to Plowshares","https://www.swords-to-plowshares.org","open","US","Veteran services","Non-citizen veteran cases"],
  [412,15,"American GI Forum","https://agifusa.org","open","US","Hispanic veteran advocacy","Chicano Vietnam veteran history"],
  [413,15,"League of United Latin American Citizens (LULAC)","https://lulac.org","open","US","400+ deported veteran cases","LULAC veteran tracking (2025)"],
  [414,15,"National Council of La Raza (UnidosUS)","https://www.unidosus.org","open","US","Hispanic policy advocacy","Hispanic veteran policy"],
  [415,15,"MALDEF Mexican American Legal Defense","https://www.maldef.org","open","US","Civil rights litigation","Chicano veteran rights"],
  [416,15,"Casa Familiar (San Ysidro)","https://www.casafamiliar.org","manual","US","Border social services","Tijuana cross-border services"],
  [417,15,"Border Angels","https://www.borderangels.org","open","US","Humanitarian data","Deported veteran humanitarian needs"],
  [418,15,"Al Otro Lado","https://alotrolado.org","open","MX","Border legal services","Deportee legal services Tijuana"],
  [419,15,"CLINIC Catholic Legal Immigration Network","https://cliniclegal.org","open","US","Immigration legal resources","Catholic legal advocacy"],
  [420,15,"National Immigrant Justice Center","https://immigrantjustice.org","open","US","Case litigation data","Deported veteran impact litigation"],
  [421,15,"PBS Frontline 'American Exile' (2021)","https://www.pbs.org/wgbh/frontline/","open","US","Documentary footage/data","Valenzuela brothers documentation"],
  [422,15,"The War Horse (Military Journalism)","https://thewarhorse.org","open","US","Investigative journalism","Deported veteran investigations"],
  [423,15,"Military Times Archive","https://www.militarytimes.com","open","US","News archive","Named Marine cases 2015-present"],
  [424,15,"ProPublica Immigration Data","https://www.propublica.org","open","US","Investigative data","Deportation journalism records"],
  [425,15,"Documented New York","https://documentedny.com","open","US","Immigration news data","NY non-citizen veteran cases"],
  // SECTION 16 — Legal Databases (426-443)
  [426,16,"Westlaw (Thomson Reuters)","https://legal.thomsonreuters.com","sub","US","Full case law","Comprehensive legal research"],
  [427,16,"LexisNexis","https://www.lexisnexis.com","sub","US","Case law, statutes","Immigration, military law"],
  [428,16,"Bloomberg Law","https://pro.bloomberglaw.com","sub","US","Legal research platform","Veteran deportation case law"],
  [429,16,"CourtListener Free Law Project","https://www.courtlistener.com","open","US","Federal court opinions","Free PACER alternative"],
  [430,16,"RECAP Archive","https://free.law/recap/","open","US","PACER documents","Free federal case documents"],
  [431,16,"Harvard Caselaw Access Project","https://case.law","key","US","6.7M cases (360M pages)","Historical immigration law"],
  [432,16,"Justia Legal Research","https://law.justia.com","open","US","Case law, statutes","Free legal research"],
  [433,16,"Casetext","https://casetext.com","open","US","Case law","Immigration precedent"],
  [434,16,"Google Scholar (Case Law)","https://scholar.google.com","open","US","Federal/state opinions","BISG, non-citizen military cases"],
  [435,16,"HeinOnline Legal History","https://heinonline.org","sub","US","Legal journals, statutes","Historical INA legislative history"],
  [436,16,"Law.gov","https://www.law.gov","open","US","Federal legal materials","Primary legal sources"],
  [437,16,"Cornell Legal Information Institute","https://www.law.cornell.edu","open","US","US Code, regulations","INA, IIRIRA, NDAA"],
  [438,16,"National Security Archive Legal Resources","https://nsarchive.gwu.edu","open","US","Declassified legal docs","Vietnam-era legal history"],
  [439,16,"Immigration Case Law (EOIR)","https://www.justice.gov/eoir","open","US","BIA published decisions","Non-citizen veteran removal appeals"],
  [440,16,"Lawfare Blog","https://www.lawfaremedia.org","open","US","National security law analysis","Military immigration law commentary"],
  [441,16,"Just Security","https://www.justsecurity.org","open","US","National security law","Non-citizen service rights analysis"],
  [442,16,"American Journal of International Law","https://www.cambridge.org","sub","US","International law","Veteran deportation international law"],
  [443,16,"Immigrant Rights Clinic Database","https://law.yale.edu","manual","US","Clinic case data","Yale immigrant rights cases"],
  // SECTION 17 — Newspaper & Press (444-469)
  [444,17,"Chronicling America (LoC)","https://chroniclingamerica.loc.gov","open","US","Historical newspapers 1770-1963","Spanish-surname press coverage"],
  [445,17,"LoC Text Services (OCR)","https://www.loc.gov/apis/micro-services/text-services/","open","US","OCR newspaper text","Full-text historical search"],
  [446,17,"LoC Image Services (IIIF)","https://www.loc.gov/apis/micro-services/image-services/","open","US","Newspaper page images","Image evidence extraction"],
  [447,17,"ProQuest Historical Newspapers","https://about.proquest.com","sub","US","Major newspaper archives","NYT, LAT, Chicago Tribune Vietnam"],
  [448,17,"ProQuest Ethnic NewsWatch","https://about.proquest.com","sub","US","Ethnic/minority press","La Opinión, Aztlán coverage"],
  [449,17,"Gale Newspapers","https://www.gale.com","sub","US","Historical newspapers","Vietnam-era coverage"],
  [450,17,"HNDM (Mexico)","https://hndm.iib.unam.mx","open","MX","1,181 Mexican periodicals","Spanish-language Vietnam coverage"],
  [451,17,"La Opinión Archives","https://laopinion.com","open","US","Spanish-language LA press","Chicano community Vietnam coverage"],
  [452,17,"El Diario de El Paso","https://www.diario.com.mx","open","MX","Border press","El Paso-CJ veteran stories"],
  [453,17,"La Prensa San Antonio","https://www.laprensa.com","open","US","Texas Spanish-language press","TX Chicano Vietnam coverage"],
  [454,17,"El Fronterizo Tijuana","https://hndm.iib.unam.mx","open","MX","Tijuana border press","Deportee stories border press"],
  [455,17,"Los Angeles Times Digital Archive","https://www.latimes.com","open","US","LAT digital archive","Chicano Moratorium August 1970"],
  [456,17,"San Diego Union-Tribune Archive","https://www.sandiegouniontribune.com","open","US","SD press","Tijuana border veteran stories"],
  [457,17,"New York Times Archive","https://www.nytimes.com","key","US","NYT digital archive","Vietnam-era national coverage"],
  [458,17,"Washington Post Archive","https://www.washingtonpost.com","open","US","WaPo digital archive","Congressional, policy coverage"],
  [459,17,"NPR Story Corps (Audio)","https://storycorps.org","open","US","Audio oral histories","Veteran oral history recordings"],
  [460,17,"ProPublica Data Store","https://www.propublica.org","open","US","Investigative datasets","Immigration enforcement data"],
  [461,17,"The Guardian US Immigration Coverage","https://www.theguardian.com","open","INT","News coverage","Deported veteran stories"],
  [462,17,"Univision Digital Archive","https://www.univision.com","open","US","Spanish TV/news archive","Hispanic veteran community coverage"],
  [463,17,"Telemundo Digital Archive","https://www.telemundo.com","open","US","Spanish TV/news archive","Deportation coverage Spanish-language"],
  [464,17,"KPBS San Diego (NPR)","https://www.kpbs.org","open","US","Border journalism","Tijuana deported veteran stories"],
  [465,17,"El Universal Mexico","https://www.eluniversal.com.mx","open","MX","Major Mexico newspaper","Mexican deportee coverage"],
  [466,17,"Reforma Mexico","https://www.reforma.com","sub","MX","Mexico newspaper","Mexican deportee coverage"],
  [467,17,"Excélsior Mexico","https://www.excelsior.com.mx","open","MX","Mexico newspaper","Historical Mexico press"],
  [468,17,"El Norte Monterrey","https://www.elnorte.com","sub","MX","NL newspaper","Northern Mexico border context"],
  [469,17,"Zeta Tijuana (Investigative)","https://zetatijuana.com","open","MX","Tijuana investigative press","Tijuana shelter, veteran coverage"],
  // SECTION 18 — Genealogy & Civil Records (470-491)
  [470,18,"FamilySearch API","https://www.familysearch.org","key","INT","5B+ genealogical records","Surname, birth, death records"],
  [471,18,"FamilySearch Mexico Records","https://www.familysearch.org","open","MX","Mexico civil/parish records","Mexico-side identity verification"],
  [472,18,"Ancestry.com Military Records","https://www.ancestry.com","sub","US","Military service records","Service verification"],
  [473,18,"Ancestry.com Immigration Records","https://www.ancestry.com","sub","US","Immigration records","Non-citizen arrival records"],
  [474,18,"FindMyPast Military Records","https://www.findmypast.com","sub","INT","UK/US military records","Cross-reference service records"],
  [475,18,"MyHeritage Military Records","https://www.myheritage.com","sub","INT","International records","Cross-border genealogy"],
  [476,18,"Vietnam Veterans Oral History Project (LoC)","https://www.loc.gov","open","US","Video/audio oral histories","Non-citizen veteran testimony"],
  [477,18,"Fold3 Military Records","https://www.fold3.com","sub","US","Military records archive","Vietnam-era service verification"],
  [478,18,"Tombstone Transcription Project","https://www.tombstones.com","open","US","Burial records","KIA burial confirmation"],
  [479,18,"Find A Grave","https://www.findagrave.com","key","US","Burial/memorial records","Vietnam KIA burial records"],
  [480,18,"BillionGraves","https://billiongraves.com","key","INT","Global burial records","Military burial verification"],
  [481,18,"NARA Genealogy Research","https://www.archives.gov","open","US","NARA genealogy resources","Military family research"],
  [482,18,"LDS Family History Library","https://www.familysearch.org","manual","INT","Microfilm records","Mexican civil records"],
  [483,18,"Mexico Civil Registry Digital","https://www.familysearch.org","key","MX","Birth/death/marriage records","Mexico-side identity verification"],
  [484,18,"NARA Mexican Border Crossing Records","https://catalog.archives.gov/id/1243733","open","US","Border crossing cards 1895-1964","Non-citizen entry documentation"],
  [485,18,"Ellis Island Records","https://www.libertyellisfoundation.org","open","US","Immigration arrival records","Earlier non-citizen entry"],
  [486,18,"Ancestry Immigration Records Mexico","https://www.ancestry.com","sub","US","Mexican immigration records","Non-citizen entry patterns"],
  [487,18,"NARA Naturalization Records","https://catalog.archives.gov","open","US","Naturalization petitions","INA §328/329 naturalization records"],
  [488,18,"USCitizenship.info Natural Records","https://uscitizenship.info","open","US","Citizenship research guide","Naturalization research tool"],
  [489,18,"VietnamWar.com Veteran Locator","https://www.vietnamwar.com","open","US","Vietnam veteran directory","Veteran identification"],
  [490,18,"Oral History Association","https://www.oralhistory.org","open","US","Oral history standards","UN oral history precedent documentation"],
  [491,18,"Smithsonian Center for Folklife","https://folklife.si.edu","manual","US","Cultural oral histories","Chicano Vietnam veteran stories"],
  // SECTION 19 — International Organizations (492-511)
  [492,19,"IOM International Organization for Migration","https://www.iom.int","open","INT","Migration data global","Mexico-US deportation context"],
  [493,19,"IOM DTM Displacement Tracking Matrix","https://dtm.iom.int","open","INT","Displacement data","Displaced veteran populations"],
  [494,19,"UNHCR Mexico","https://www.unhcr.org/mx","open","INT","Refugee data Mexico","Deportee refugee context"],
  [495,19,"UNHCR Global Trends","https://www.unhcr.org","open","INT","Global refugee stats","International non-citizen veteran context"],
  [496,19,"ILO International Labor Organization","https://www.ilo.org","open","INT","Global labor data","Non-citizen worker rights context"],
  [497,19,"OECD Migration Data","https://www.oecd.org/migration/","open","INT","International migration data","Cross-border veteran policy compare"],
  [498,19,"UN Human Rights Office","https://www.ohchr.org","open","INT","Human rights reports","Veteran deportation rights documentation"],
  [499,19,"UN Special Rapporteur on Migration","https://www.ohchr.org","open","INT","Migration rights reports","Deported veteran international rights"],
  [500,19,"Inter-American Court of Human Rights","https://www.corteidh.or.cr","open","INT","Case law, advisory opinions","Regional human rights law"],
  [501,19,"Inter-American Commission on Human Rights","https://www.oas.org/en/iachr/","open","INT","IACHR reports","Mexico-side veteran rights"],
  [502,19,"OAS Organization of American States","https://www.oas.org","open","INT","Hemispheric reports","US-Mexico bilateral context"],
  [503,19,"NATO Research","https://www.nato.int","open","INT","Military research","Non-citizen allied military service"],
  [504,19,"World Bank Migration Data","https://www.worldbank.org","open","INT","Global migration stats","Remittance, deportee economic data"],
  [505,19,"World Bank Open Data","https://data.worldbank.org","open","INT","Development indicators","Mexico economic context"],
  [506,19,"IADB Inter-American Development Bank","https://www.iadb.org","open","INT","Latin America development data","Mexico deportee economic integration"],
  [507,19,"UNESCO Cultural Heritage Database","https://whc.unesco.org","open","INT","Cultural data","Chicano cultural documentation"],
  [508,19,"Red Cross International Tracing Service","https://www.icrc.org","manual","INT","POW/MIA tracing","Missing veteran location"],
  [509,19,"ACNUR (UNHCR Mexico)","https://www.acnur.org/mx","open","INT","Refugee data Mexico","Mexico asylum context"],
  [510,19,"Global Detention Project","https://www.globaldetentionproject.org","open","INT","Immigration detention data","Veteran detention documentation"],
  [511,19,"Geneva Academy","https://www.geneva-academy.ch","open","INT","International humanitarian law","Non-citizen military IHL context"],
  // SECTION 20 — Scholarly Aggregators (512-535)
  [512,20,"PubMed / MEDLINE","https://pubmed.ncbi.nlm.nih.gov","open","US","Biomedical literature","PTSD, deportation health research"],
  [513,20,"PsycINFO (APA)","https://www.apa.org","sub","US","Psychology research","PTSD, veteran mental health"],
  [514,20,"JSTOR Global Plants","https://plants.jstor.org","open","US","Open JSTOR content","Open access research"],
  [515,20,"Google Scholar","https://scholar.google.com","open","INT","Broad academic search","Citation discovery"],
  [516,20,"Microsoft Academic","https://academic.microsoft.com","open","INT","Academic knowledge graph","Research network mapping"],
  [517,20,"LENS.org Scholarly Search","https://www.lens.org","key","INT","200M+ scholarly works","Patent + paper search"],
  [518,20,"DOAJ Directory of Open Access Journals","https://doaj.org","open","INT","Open access journals","Free full-text research"],
  [519,20,"BASE Bielefeld Academic Search","https://www.base-search.net","open","INT","300M+ documents","Chicano studies, immigration"],
  [520,20,"EBSCO Discovery Service","https://connect.ebsco.com","sub","INT","Full academic discovery","Comprehensive literature review"],
  [521,20,"ProQuest One Academic","https://about.proquest.com","sub","INT","Multi-database search","Military, immigration research"],
  [522,20,"Gale Academic OneFile","https://www.gale.com","sub","INT","Academic journals","Vietnam-era Chicano scholarship"],
  [523,20,"Annual Reviews","https://www.annualreviews.org","sub","INT","Review articles","Military demographics reviews"],
  [524,20,"Oxford Academic (OUP Journals)","https://academic.oup.com","sub","INT","Oxford journals","Journal of Veterans Studies target"],
  [525,20,"Cambridge Core","https://www.cambridge.org","key","INT","Cambridge journals","APSR replication archive reference"],
  [526,20,"Wiley Online Library","https://onlinelibrary.wiley.com","sub","INT","Wiley journals","Immigration, sociology journals"],
  [527,20,"SAGE Journals","https://journals.sagepub.com","sub","INT","SAGE social science","Chicano, Latino studies"],
  [528,20,"Taylor & Francis Online","https://www.tandfonline.com","sub","INT","T&F journals","Military sociology journals"],
  [529,20,"Springer Nature","https://link.springer.com","key","INT","Science/social science","Behavioral research"],
  [530,20,"Elsevier ScienceDirect","https://www.sciencedirect.com","key","INT","Science/social science","BISG methodology, demography"],
  [531,20,"JSTOR Arts & Sciences","https://www.jstor.org","key","INT","Humanities/social science","Chicano studies journals"],
  [532,20,"Emerald Insight","https://www.emerald.com","sub","INT","Management/social science","Public administration journals"],
  [533,20,"Directory of Open Access Books (DOAB)","https://www.doabooks.org","open","INT","Open access books","Free full-text books"],
  [534,20,"Internet Archive Scholar","https://scholar.archive.org","open","INT","35M+ open papers","Historical document preservation"],
  [535,20,"Internet Archive (Wayback Machine)","https://web.archive.org","open","INT","Web archive","Archived government pages"],
  // SECTION 21 — Geospatial & GIS (536-551)
  [536,21,"Census TIGER/Line Shapefiles","https://www.census.gov","open","US","US geographic boundaries","BISG geographic priors"],
  [537,21,"ArcGIS Living Atlas","https://livingatlas.arcgis.com","open","INT","Global geospatial data","Shelter location mapping"],
  [538,21,"ArcGIS Hub (Federal)","https://hub.arcgis.com","open","US","Government GIS data","Border infrastructure"],
  [539,21,"OpenStreetMap","https://www.openstreetmap.org","open","INT","Global map data","Shelter locations, border crossing"],
  [540,21,"Mapbox","https://www.mapbox.com","key","INT","Map tiles, geocoding","Platform base maps"],
  [541,21,"Google Maps Platform","https://developers.google.com/maps","key","INT","Maps, geocoding","Shelter location services"],
  [542,21,"USGS National Map","https://www.usgs.gov","open","US","US topographic data","Border region geographic data"],
  [543,21,"Bureau of Transportation Statistics GIS","https://www.bts.gov","open","US","Transportation GIS","Border crossing data"],
  [544,21,"FEMA Hazard Maps","https://msc.fema.gov","open","US","Flood/hazard maps","Shelter infrastructure"],
  [545,21,"DHS HIFLD Geospatial Data","https://hifld-geoplatform.hub.arcgis.com","open","US","Critical infrastructure","Border facilities data"],
  [546,21,"Mexico INEGI Geographic Data","https://www.inegi.org.mx","open","MX","Mexico GIS data","Mexico shelter mapping"],
  [547,21,"Mexico CONABIO Geospatial","https://www.conabio.gob.mx","open","MX","Mexico environmental GIS","Geographic context"],
  [548,21,"Carto Platform","https://carto.com","key","INT","Spatial analytics","Deportation heatmaps"],
  [549,21,"Palantir Gotham (OSINT GIS)","https://www.palantir.com","manual","INT","Intelligence GIS","Advanced geospatial analysis"],
  [550,21,"Social Explorer","https://www.socialexplorer.com","key","US","Census demographic maps","Hispanic population mapping"],
  [551,21,"PolicyMap","https://www.policymap.com","key","US","Social data maps","Veteran population GIS"],
  // SECTION 22 — DACA & Immigration Reform (552-565)
  [552,22,"USCIS DACA Data","https://www.uscis.gov/DACA","open","US","DACA approvals by state","DACA-veteran intersection"],
  [553,22,"USCIS DACA Quarterly Reports","https://www.uscis.gov","open","US","DACA recipient data","Non-citizen service eligibility"],
  [554,22,"National Immigration Law Center DACA Resources","https://www.nilc.org","open","US","DACA policy, legal analysis","DACA veteran intersection"],
  [555,22,"DACA Military Service Data","https://www.defense.gov","foia","US","DACA enlistees","DACA-military service tracking"],
  [556,22,"Center for American Progress DACA Data","https://www.americanprogress.org","open","US","DACA analysis","DACA veteran policy"],
  [557,22,"DREAM Act Legislative History","https://www.congress.gov","key","US","DREAM Act bills","Legislative tracking"],
  [558,22,"American Dream and Promise Act","https://www.congress.gov","key","US","Current legislation","Veteran protections"],
  [559,22,"Congressional Hispanic Caucus DACA Tracker","https://chc.house.gov","open","US","CHC policy positions","CHC briefing support"],
  [560,22,"Immigrant Youth Coalition","https://www.immigrantyouth.org","open","US","Youth immigrant advocacy","DACA veteran generation"],
  [561,22,"United We Dream","https://unitedwedream.org","open","US","DACA advocacy network","Undocumented veteran community"],
  [562,22,"FWD.us Technology Immigration","https://www.fwd.us","open","US","Immigration reform data","Tech industry immigration advocacy"],
  [563,22,"National DACA Legal Support Line","https://www.ilrc.org","open","US","Legal DACA resources","Non-citizen veteran legal support"],
  [564,22,"DACA Impact Study (CATO)","https://www.cato.org","open","US","DACA economic research","DACA veteran economic contribution"],
  [565,22,"International Institute of Education (IIE)","https://www.iie.org","open","US","International student data","Non-citizen educational context"],
];

// Convert raw to structured objects
export const SOURCES = SOURCES_RAW.map(([n, sec, name, url, access, country, data, use]) => ({
  n, sec, name, url, access, country, data, use
}));
