// Border Shelter Data — Veteran concentration, ICE enforcement, legal resources

export const SHELTER_LOCATIONS = [
  {
    id: "S001",
    city: "Tijuana",
    state: "BC",
    country: "Mexico",
    lat: 32.5149,
    lng: -117.0382,
    name: "Casa del Migrante",
    veterans: 200,
    veteranPct: 8.5,
    capacity: 2350,
    iceDangerLevel: 9,
    iceActivityScore: 0.94,
    iceRaidFreq: "2-3/week",
    legalResources: ["ACLU San Diego", "RAICES", "Al Otro Lado"],
    nearestLegal: { name: "ACLU San Diego", distance: 3.2, hours: "9am-5pm" },
    shelterType: "Albergue",
    cases: ["C002", "C003"],
    notes: "Highest concentration. Active ICE surveillance documented.",
  },
  {
    id: "S002",
    city: "Ciudad Juárez",
    state: "CHIH",
    country: "Mexico",
    lat: 31.7619,
    lng: -106.4850,
    name: "Albergue del Desierto",
    veterans: 80,
    veteranPct: 6.2,
    capacity: 1280,
    iceDangerLevel: 8,
    iceActivityScore: 0.87,
    iceRaidFreq: "2/week",
    legalResources: ["Las Americas Immigrant Advocacy Center", "VIVO"],
    nearestLegal: { name: "Las Americas IAC", distance: 5.1, hours: "8am-4pm" },
    shelterType: "Albergue",
    cases: [],
    notes: "Second-largest. Proximity to El Paso high-enforcement zone.",
  },
  {
    id: "S003",
    city: "Nogales",
    state: "SON",
    country: "Mexico",
    lat: 31.3386,
    lng: -110.9876,
    name: "Casa Migrante de Nogales",
    veterans: 35,
    veteranPct: 5.8,
    capacity: 600,
    iceDangerLevel: 7,
    iceActivityScore: 0.72,
    iceRaidFreq: "1-2/week",
    legalResources: ["Coalición de Derechos Humanos", "Borderlands Coalition"],
    nearestLegal: { name: "Coalición DH", distance: 2.8, hours: "10am-4pm" },
    shelterType: "Albergue",
    cases: ["C005"],
    notes: "Nogales Arizona-Sonora crossing point. Active CBPO presence.",
  },
  {
    id: "S004",
    city: "Matamoros",
    state: "TAM",
    country: "Mexico",
    lat: 25.8725,
    lng: -97.5000,
    name: "Casa del Migrante Matamoros",
    veterans: 25,
    veteranPct: 4.1,
    capacity: 610,
    iceDangerLevel: 6,
    iceActivityScore: 0.68,
    iceRaidFreq: "1/week",
    legalResources: ["Valle Grande Legal Services", "Southern Poverty Law Center"],
    nearestLegal: { name: "Valle Grande LS", distance: 8.5, hours: "9am-3pm" },
    shelterType: "Albergue",
    cases: [],
    notes: "McAllen-Reynosa crossing. Lower enforcement than Texas Valley.",
  },
  {
    id: "S005",
    city: "Nuevo Laredo",
    state: "TAM",
    country: "Mexico",
    lat: 27.4712,
    lng: -99.5265,
    name: "Albergue del Espíritu Santo",
    veterans: 20,
    veteranPct: 3.5,
    capacity: 570,
    iceDangerLevel: 7,
    iceActivityScore: 0.75,
    iceRaidFreq: "2/week",
    legalResources: ["Texas RioGrande Legal Aid", "MALDEF"],
    nearestLegal: { name: "TxRG Legal Aid", distance: 12.0, hours: "8am-5pm" },
    shelterType: "Albergue",
    cases: [],
    notes: "International Bridge crossing. High truck inspection activity.",
  },
  {
    id: "S006",
    city: "Reynosa",
    state: "TAM",
    country: "Mexico",
    lat: 26.0961,
    lng: -97.4992,
    name: "Casa del Migrante Reynosa",
    veterans: 18,
    veteranPct: 3.2,
    capacity: 550,
    iceDangerLevel: 6,
    iceActivityScore: 0.70,
    iceRaidFreq: "1/week",
    legalResources: ["VALOR", "South Texas College Legal Clinic"],
    nearestLegal: { name: "VALOR", distance: 6.5, hours: "9am-4pm" },
    shelterType: "Albergue",
    cases: [],
    notes: "McAllen-Reynosa crossing. Secondary port activity.",
  },
  {
    id: "S007",
    city: "Mexicali",
    state: "BC",
    country: "Mexico",
    lat: 32.6428,
    lng: -115.4542,
    name: "Albergue del Sueño",
    veterans: 15,
    veteranPct: 2.8,
    capacity: 535,
    iceDangerLevel: 5,
    iceActivityScore: 0.62,
    iceRaidFreq: "< 1/week",
    legalResources: ["San Diego Immigrant Rights Consortium", "SDRC"],
    nearestLegal: { name: "SDRC", distance: 3.5, hours: "8am-5pm" },
    shelterType: "Albergue",
    cases: [],
    notes: "Calexico-Mexicali crossing. Lower overall enforcement.",
  },
];

export const ICE_ENFORCEMENT_REGIONS = [
  {
    id: "REGION-SD",
    name: "San Diego Sector",
    operationalArea: "San Ysidro to El Centro",
    agents: 750,
    arrestsPerMonth: 1850,
    avgVetArrests: 12,
    dangerLevel: 9,
    apprehensionRate: 0.87,
    sheltersCovered: ["S001", "S007"],
  },
  {
    id: "REGION-ELP",
    name: "El Paso Sector",
    operationalArea: "New Mexico to Ojinaga",
    agents: 680,
    arrestsPerMonth: 1650,
    avgVetArrests: 8,
    dangerLevel: 8,
    apprehensionRate: 0.82,
    sheltersCovered: ["S002", "S003"],
  },
  {
    id: "REGION-RGV",
    name: "Rio Grande Valley Sector",
    operationalArea: "Corpus Christi to Brownsville",
    agents: 720,
    arrestsPerMonth: 2100,
    avgVetArrests: 14,
    dangerLevel: 8,
    apprehensionRate: 0.85,
    sheltersCovered: ["S004", "S005", "S006"],
  },
];

export const LEGAL_SUPPORT_RESOURCES = [
  {
    id: "LSR-ACLU-SD",
    org: "ACLU San Diego",
    type: "Civil Rights / Immigration",
    location: { city: "San Diego", state: "CA", lat: 32.7157, lng: -117.1611 },
    phone: "(619) 232-2121",
    hours: "9am-5pm Mon-Fri",
    specialties: ["Veteran Rights", "Deportation Defense", "FOIA Support"],
    vetSpecialist: true,
    coverageArea: ["San Diego", "Tijuana"],
  },
  {
    id: "LSR-RAICES",
    org: "RAICES (Refugee and Immigrant Center for Education and Legal Services)",
    type: "Immigration Justice",
    location: { city: "San Antonio", state: "TX", lat: 29.4241, lng: -98.4936 },
    phone: "(210) 569-4024",
    hours: "9am-5pm Mon-Fri",
    specialties: ["Veteran Protection", "IIRIRA Appeals", "Legal Representation"],
    vetSpecialist: true,
    coverageArea: ["Rio Grande Valley", "San Antonio"],
  },
  {
    id: "LSR-ALO",
    org: "Al Otro Lado",
    type: "Binational Defense",
    location: { city: "Tijuana", state: "BC", lat: 32.5149, lng: -117.0382 },
    phone: "+52 (664) 685-8649",
    hours: "8am-6pm Daily",
    specialties: ["Shelter Advocacy", "Repatriation", "Mexico-Side Legal Support"],
    vetSpecialist: false,
    coverageArea: ["Tijuana", "Border Region"],
  },
  {
    id: "LSR-VALOR",
    org: "VALOR",
    type: "Veteran Legal Advocacy",
    location: { city: "Brownsville", state: "TX", lat: 25.9017, lng: -97.4975 },
    phone: "(956) 542-3300",
    hours: "9am-4pm Mon-Fri",
    specialties: ["Military Service Defense", "SCRA Enforcement", "Naturalization Barriers"],
    vetSpecialist: true,
    coverageArea: ["Rio Grande Valley", "Reynosa", "Matamoros"],
  },
  {
    id: "LSR-COALITION-DH",
    org: "Coalición de Derechos Humanos",
    type: "Human Rights Advocacy",
    location: { city: "Nogales", state: "AZ", lat: 31.3386, lng: -110.9876 },
    phone: "+52 (631) 316-7979",
    hours: "10am-4pm Mon-Fri",
    specialties: ["Border Enforcement Monitoring", "Shelter Advocacy", "Cross-Border Support"],
    vetSpecialist: false,
    coverageArea: ["Nogales", "Sonora Region"],
  },
];

export const DEPORTATION_RISK_BY_STATE = {
  CA: { state: "California", vets: 42000, riskScore: 0.82, iceAgents: 1200, shelters: 2 },
  TX: { state: "Texas", vets: 38000, riskScore: 0.88, iceAgents: 1850, shelters: 4 },
  AZ: { state: "Arizona", vets: 18000, riskScore: 0.79, iceAgents: 850, shelters: 1 },
};