// Canonical Terminel–Sagasta entities — updated May 20 2026 (Session expansion: 10→40 entities)
export const seedEntities = [
  // ── PEOPLE ──
  { entity_type: 'person', name: 'Francisco L. Terminel',
    aka: ['F. L. Terminel', 'Verminel', 'Francisco Terminel', 'F. Terminel'],
    role_tags: ['haciendado', 'senador_desaforado', 'diputado', 'operador_callista', 'exiliado_san_diego'],
    description: 'Central subject. Federal Senator desaforado Dec 14 1935. San Diego exile 1935–1940+. Operated mining infrastructure (water, dams, bridges) in San Javier. Used proxy network across 45+ years.' },
  { entity_type: 'person', name: 'Aviana Sagasta',
    aka: ['Avina Sagasta', 'Abina Sagasta', 'Aviana'],
    role_tags: ['concubina', 'titular_nominal', 'escudo_de_activos'],
    description: 'Indigenous concubine of Francisco. Probable Névome Pima Bajo affiliation (50–65%). Nominal titleholder on asserted land deeds. No community-property rights under Mexican Civil Code. Denied at WF office mid-1930s. Left with one cow.' },
  { entity_type: 'person', name: 'María Manuela Terminel Sagasta',
    aka: ['Nela'],
    role_tags: ['hija', 'fuente_oral_primaria'],
    description: 'Daughter of Francisco × Aviana. Born Aug 7 1910 San Javier. Died 2012 Ontario CA age 101. Primary oral-history conduit. Never knew Francisco became a senator.' },
  { entity_type: 'person', name: 'Manuel Terminel hijo',
    aka: ['Manuel Terminel'],
    role_tags: ['operador_obregonista', 'haciendado_mayo', 'proxy_hermano'],
    description: 'Francisco\'s brother. Presidente Efectivo Cámara Agrícola Río Mayo (1921). Bacobampo co-owner. 1942 AHORA donor 500 pesos. Obregonista anchor — survived Francisco\'s callista collapse.' },
  { entity_type: 'person', name: 'Nicolás C. Terminel',
    aka: ['Nicolás Terminel'],
    role_tags: ['proxy_hermano', 'haciendado'],
    description: 'Francisco\'s brother. Bacobampo co-owner. 1942 AHORA donor 300 pesos.' },
  { entity_type: 'person', name: 'Luis Porchas',
    aka: ['L. Porchas'],
    role_tags: ['concesionario_minero', 'proxy_operacional'],
    description: 'San Javier mining concessionaire. Mina Las Goteras SJ-16 (SGM 2006). Porchas held concessions; Terminel held surrounding infrastructure.' },
  { entity_type: 'person', name: 'Plutarco Elías Calles',
    aka: ['Calles', 'PEC'],
    role_tags: ['patrón_político', 'exiliado'],
    description: 'Francisco\'s political patron. Exiled San Diego Apr 9 1936. Francisco\'s over-concentration in Calles was his single failure point.' },
  { entity_type: 'person', name: 'Lázaro Cárdenas',
    role_tags: ['presidente', 'reformador_agrario'],
    description: 'Ordered desafuero Dec 14 1935, Sonora dissolution Dec 16 1935, Calles exile Apr 9 1936, Bacobampo expropriation Mar 1938.' },
  { entity_type: 'person', name: 'Gov. Rafael Izábal',
    role_tags: ['gobernador_sonora', 'arquitecto_deportaciones'],
    description: 'Governor of Sonora 1903–07. Architect of Yaqui deportations. AGES Caja 193 Legajo 7 alleged Izábal–Terminel correspondence.' },
  { entity_type: 'person', name: 'Álvaro Obregón',
    role_tags: ['presidente', 'patron_obregonista'],
    description: 'Honorary President Cámara Agrícola Río Mayo 1921. Manuel hijo\'s patron.' },
  { entity_type: 'person', name: 'Carmelita Terango',
    role_tags: ['fuente_oral_viva', 'sobrina_mayor'],
    description: 'KEY LIVING ORAL-HISTORY SOURCE. Daughter of Leonor Terminel. Oldest niece of all Terminel siblings. Must be audio-recorded with consent URGENTLY.' },
  { entity_type: 'person', name: 'Leonor Terminel',
    role_tags: ['hija_mayor', 'hermana_nela'],
    description: 'Oldest of four documented Francisco × Aviana children.' },
  { entity_type: 'person', name: 'Rosa Terminel',
    role_tags: ['hija', 'hermana_nela'] },
  { entity_type: 'person', name: 'Francisco Terminel Jr.',
    role_tags: ['hijo', 'hermano_nela'] },
  { entity_type: 'person', name: 'Don José Santos Terminel Félix',
    role_tags: ['patriarca', 'fundador_linaje'],
    description: 'Documented at Los Cedros, Baroyeca-Tesopaco, 1860s. Refutes pure French-immigrant narrative.' },
  { entity_type: 'person', name: 'Gabriel T. Arce Jr.',
    role_tags: ['investigador_principal', 'descendiente'],
    description: 'Great-grandson of Francisco L. Terminel and Aviana Sagasta through Nela. Holds private title deeds (water, dams, bridges) + original Francisco letter.' },
  { entity_type: 'person', name: 'John Kenneth Turner',
    role_tags: ['periodista', 'fuente_verificada'],
    description: 'Author Barbarous Mexico (1910, on file). Documents 8,000 Yaqui slaves + American Cordage Trust in Yucatán henequen plantations.' },
  { entity_type: 'person', name: 'Dra. María Inés Aragón Salcido',
    role_tags: ['archivista', 'contacto_institucional'],
    description: 'Directora General, Archivo General de Notarías del Estado de Sonora. Tel. (662) 217-0314. Custodian of Document B (poder notarial).' },

  // ── ORGANIZATIONS ──
  { entity_type: 'organization', name: 'Wells Fargo Express',
    aka: ['Wells Fargo y Cía.', 'Compañía Mexicana de Express S.A.', 'WF Co. Express S.A.'],
    description: '223→456 Mexican offices 1900–1909. Guaymas agent A. Willard 1890. Mexican subsidiary operated 1910–1964. Primary records: Huntington Library Box 34.' },
  { entity_type: 'organization', name: 'Cámara Agrícola del Río Mayo',
    aka: ['Canaco Servitur del Mayo'],
    description: 'Founded Jun 19 1921 at Manuel Terminel hijo\'s residence. Manuel = Presidente Efectivo; Obregón = Presidente Honorario.' },
  { entity_type: 'organization', name: 'American Cordage Trust',
    description: 'Standard Oil ramification. Absorbed >50% Yucatán henequen exports. Named by Turner in Barbarous Mexico as beneficiary of Yaqui forced labor.' },
  { entity_type: 'organization', name: 'Senate of Mexico' },
  { entity_type: 'organization', name: 'Comisión Agraria Mixta del Estado de Sonora',
    description: 'Executed Bacobampo expropriation Mar 1938 (453 ha, Terminel brothers).' },

  // ── PLACES ──
  { entity_type: 'place', name: 'San Javier, Sonora',
    description: 'INEGI municipio 260541. Founded 1706 Real de Minas. ~146km east of Hermosillo. Silver 133–1,240 g/ton. 28 of 32 mines now Ejido San Javier.' },
  { entity_type: 'place', name: 'Sahuaripa, Sonora',
    description: 'Parent municipality. Civil records catalog 704679 (1868–1994). Parish catalog 704681.' },
  { entity_type: 'place', name: 'Bacobampo, Etchojoa, Sonora',
    description: '453 hectares expropriated Mar 1938. AGES exp. 411.12"32"/174.' },
  { entity_type: 'place', name: 'San Diego, California',
    description: 'Francisco exile 1935–1940+. 700km from Hermosillo — strategically closer than CDMX.' },
  { entity_type: 'place', name: 'Guaymas, Sonora',
    description: 'WF Express agent A. Willard 1890. Registro Público de la Propiedad: Libro 92, Folio 37 (asserted 1907 deed to Aviana).' },

  // ── TRIBES ──
  { entity_type: 'tribe', name: 'Névome Pima Bajo',
    description: 'PRIMARY hypothesis for Aviana\'s affiliation (50–65%). Inhabited Sonora River watershed — exactly where San Javier is located.' },
  { entity_type: 'tribe', name: 'Yaqui',
    description: '8,000–15,000 deported 1902–1908 under Izábal/Corral. 15–25% probability for Aviana.' },

  // ── ARCHIVES ──
  { entity_type: 'archive', name: 'Huntington Library',
    description: '1151 Oxford Rd, San Marino CA 91108. Tel (626) 405-2191. Box 34 Series 2 "Investments in Mexico" 1883–1906. PRIMARY WF RECORDS — NOT WF Museum. Free access by appointment.' },
  { entity_type: 'archive', name: 'AHES', description: 'Garmendia 157 Sur, Hermosillo. Tel (662) 213-12-86.' },
  { entity_type: 'archive', name: 'Archivo General de Notarías Sonora',
    description: 'Centro de Gobierno, Edif. Sonora y Norte, Hermosillo. Dra. Aragón Salcido (662) 217-0314. Custodian: protocolos notariales (Document B).' },
  { entity_type: 'archive', name: 'Registro Público Hermosillo',
    description: 'Holds Guaymas historical records. Target: Libro 92 Folio 37 (1907 Aviana deed — Document A).' },
  { entity_type: 'archive', name: 'NARA',
    description: 'RG 84 Hermosillo (11 cu.ft.) + Nogales (42 cu.ft.). Pre-1930 open.' },
  { entity_type: 'archive', name: 'Bancroft Library',
    description: 'UC Berkeley. bancref-library@berkeley.edu. Villa 122 silver bars Apr 1913 + WF Mexican subsidiary documents.' },
  { entity_type: 'archive', name: 'FAPECFT',
    description: 'Fondo Plutarco Elías Calles / Fernando Torreblanca. Search "Terminel" + "Verminel" 1935–1940.' },
  { entity_type: 'archive', name: 'FamilySearch',
    description: 'Catalog 704679 (civil, Sahuaripa 1868–1994) + 704681 (parish Guadalupe). Free. San Javier records inside Sahuaripa collection pre-1934.' },
  { entity_type: 'archive', name: 'Pascua Yaqui Tribe — ANARÓ',
    description: '7474 S. Camino de Oeste, Tucson AZ 85757. Cultural Resources Dept. Tribal-sovereign protocol. Outreach letter drafted.' },

  // ── CASE ──
  { entity_type: 'case', name: 'Terminel–Sagasta Investigation',
    description: 'TE360 database: 94 claims · 30 entities · 34 archive targets. Score 28/100. Academic case: STRONG. Advocacy case: structurally sound, needs archive pulls.' },
];

const stripAccents = (s) => s.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
export const normalizeKey = (name) =>
  stripAccents((name || '').toLowerCase()).replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
