import { useState } from "react";
import { P, CASES } from "../../lib/teData";
import { base44 } from "../../api/base44Client";

const RISK_THRESHOLDS = {
  critical: { min: 80, color: P.red, label: "CRITICAL" },
  high: { min: 60, color: P.amber, label: "HIGH" },
  medium: { min: 40, color: P.gold, label: "MEDIUM" },
};

const calculateRiskScore = (c) => {
  let score = 0;
  if (c.status === "Deported" || c.status === "Self-Deported") score += 35;
  if (c.tier === "Gold") score += 20;
  if (c.tier === "Silver") score += 15;
  if (c.confidence >= 90) score += 15;
  if (c.confidence >= 75) score += 10;
  if (c.branch === "USMC") score += 10;
  return Math.min(score, 100);
};

const LETTER_TEMPLATE = (caseData) => `
CONGRESSIONAL HISPANIC CAUCUS
U.S. House of Representatives
Washington, DC 20515

Date: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}

RE: Urgent Inquiry — Deported Veteran Case ${caseData.id}: ${caseData.name}
    Service Records & IIRIRA Retroactive Deportation Risk

Dear Chairperson and CHC Members:

The AUMER Foundation urgently seeks CHC assistance regarding the deportation case of ${caseData.name} (Case ${caseData.id}), a ${caseData.branch} veteran whose service to the United States is now at immediate risk under retroactive IIRIRA §237(a)(2)(A)(iii) application.

CASE SUMMARY:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Case ID:              ${caseData.id}
Name:                 ${caseData.name}
Service Branch:       ${caseData.branch}
Service Status:       ${caseData.status}
Country of Service:   ${caseData.country}
Verification Tier:    ${caseData.tier} (${caseData.confidence}% confidence)
Current Status:       ${caseData.status}
Deportation Risk:     CRITICAL (${calculateRiskScore(caseData)}/100)

CRITICAL FACTS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. INA §329 Violation
   — ${caseData.name} served honorably during wartime, entitling them to expedited
     naturalization under INA §329.
   — USCIS has NOT issued expedited naturalization despite lawful service.
   — Retroactive IIRIRA application denies judicial discretion previously held.

2. Retroactive Deportation Under IIRIRA
   — IIRIRA §237(a)(2)(A)(iii) retroactively applies criminal bars to pre-1996
     offenses not originally deemed deportable.
   — No notice provided to service member or VA.
   — Service records do NOT trigger mandatory notification to ICE (no VA-ICE MOU).

3. Verification Status
   — ${caseData.tier}-tier certification by CB-HSIVF consortium.
   — SHA-256 cryptographic chain of custody verified.
   — Case file available for Congressional review.

IMMEDIATE ACTIONS REQUIRED:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. Request DHS Secretary issue formal administrative stay of removal pending
   Congressional review of military service record.

2. Request VA Secretary confirm service record and INA §329 eligibility.

3. Request USCIS explain N-400 denial (if applicable) and IIRIRA retroactive
   application rationale.

4. Support S.874 (Veterans Visa Act) for expedited visa pathway if removal proceeds.

LEGISLATIVE NEXUS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• S.874:    Veterans Visa Act — expedited visa pathway for deported veterans
• HR.1537:  Repatriate Our Patriots Act — VA healthcare for deported veterans
• Ask #3:   IIRIRA §237 Partial Repeal (judicial discretion restoration)
• Ask #5:   Mandatory VA-ICE Data Sharing (notification mandate)

AUMER FOUNDATION CONTACT:
Gabriel T. Arce Jr. | gtarce@usc.edu | (760) 453-8421

Respectfully submitted,

AUMER Foundation
EIN: 99-0495658
Forensic Civic Intelligence Platform: TruthEngine360

---
This letter was generated by TruthEngine360 CHC Inquiry Letter Generator
Case verified and cryptographically certified for Congressional briefing use.
`;

export default function CHCInquiryLetterGenerator() {
  const [selectedCase, setSelectedCase] = useState(null);
  const [letterText, setLetterText] = useState("");
  const [copied, setCopied] = useState(false);
  const [sending, setSending] = useState(false);
  const [recipientEmail, setRecipientEmail] = useState("chc@mail.house.gov");

  // Filter critical cases
  const criticalCases = CASES.map(c => ({
    ...c,
    riskScore: calculateRiskScore(c),
  })).filter(c => calculateRiskScore(c) >= 80);

  const handleGenerateLetter = (caseItem) => {
    setSelectedCase(caseItem);
    const letter = LETTER_TEMPLATE(caseItem);
    setLetterText(letter);
  };

  const handleCopyToClipboard = () => {
    navigator.clipboard.writeText(letterText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSendEmail = async () => {
    if (!letterText || !selectedCase) return;
    setSending(true);
    await base44.integrations.Core.SendEmail({
      to: recipientEmail,
      subject: `[AUMER] CHC Urgent Inquiry — Deported Veteran ${selectedCase.id}: ${selectedCase.name}`,
      body: letterText,
    });
    setSending(false);
  };

  const handleExportPDF = async () => {
    if (!letterText) return;
    const blob = new Blob([letterText], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `CHC_Inquiry_${selectedCase.id}_${selectedCase.name.replace(/\s/g, "_")}.txt`;
    a.click();
  };

  return (
    <div>
      <div style={{ marginBottom: 12 }}>
        <div style={{ fontSize: 13, fontWeight: 800, color: P.t1 }}>
          🏛️ CHC Inquiry Letter <span style={{ color: P.red }}>Generator</span>
        </div>
        <div style={{ fontSize: 7, color: P.t4, letterSpacing: 2 }}>
          AUTOMATED CONGRESSIONAL INQUIRY DRAFTING · IIRIRA RETROACTIVE DEPORTATION
        </div>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "320px 1fr", gap: 12 }}>
        {/* Case selector */}
        <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
          <div style={{ background: P.card, border: `1px solid ${P.b}`, borderRadius: 10, padding: "12px 14px" }}>
            <div style={{ fontSize: 8, fontWeight: 700, color: P.red, letterSpacing: 1, marginBottom: 10 }}>
              🚨 CRITICAL RISK CASES — {criticalCases.length}
            </div>
            {criticalCases.length === 0 ? (
              <div style={{ fontSize: 8, color: P.t4 }}>No critical cases found.</div>
            ) : (
              criticalCases.map((c) => {
                const isSelected = selectedCase?.id === c.id;
                return (
                  <div
                    key={c.id}
                    onClick={() => handleGenerateLetter(c)}
                    style={{
                      background: isSelected ? `${P.red}15` : "#080D18",
                      border: `1px solid ${isSelected ? P.red : P.b}`,
                      borderLeft: `4px solid ${P.red}`,
                      borderRadius: 8,
                      padding: "9px 11px",
                      marginBottom: 7,
                      cursor: "pointer",
                    }}
                  >
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 3 }}>
                      <span style={{ fontFamily: "'IBM Plex Mono',monospace", fontSize: 9, fontWeight: 800, color: P.red }}>
                        {c.id}
                      </span>
                      <span style={{ fontSize: 10, fontWeight: 800, color: P.red }}>{c.riskScore}</span>
                    </div>
                    <div style={{ fontSize: 8, color: P.t2, fontWeight: 700 }}>{c.name}</div>
                    <div style={{ fontSize: 7, color: P.t4, marginTop: 2 }}>
                      {c.branch} · {c.tier} · {c.status}
                    </div>
                  </div>
                );
              })
            )}
          </div>

          {selectedCase && (
            <div style={{ background: P.card, border: `1px solid ${P.gold}30`, borderRadius: 10, padding: "10px 12px" }}>
              <div style={{ fontSize: 7, color: P.gold, fontWeight: 700, letterSpacing: 1, marginBottom: 8 }}>
                SELECTED CASE
              </div>
              <div style={{ fontSize: 8, color: P.t2, fontWeight: 700, marginBottom: 3 }}>
                {selectedCase.name}
              </div>
              <div style={{ fontSize: 7, color: P.t4, lineHeight: 1.7 }}>
                <div>Risk: <span style={{ color: P.red, fontWeight: 700 }}>{selectedCase.riskScore}/100</span></div>
                <div>Branch: {selectedCase.branch}</div>
                <div>Status: {selectedCase.status}</div>
                <div style={{ marginTop: 6, paddingTop: 6, borderTop: `1px solid ${P.b}20` }}>
                  {selectedCase.notes}
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Letter preview */}
        <div style={{ background: P.card, border: `1px solid ${P.b}`, borderRadius: 10, display: "flex", flexDirection: "column" }}>
          <div style={{ padding: "10px 14px", borderBottom: `1px solid ${P.b}` }}>
            <div style={{ fontSize: 8, fontWeight: 700, color: P.t2, letterSpacing: 1 }}>
              📧 LETTER PREVIEW
            </div>
          </div>

          {letterText ? (
            <>
              <textarea
                readOnly
                value={letterText}
                style={{
                  flex: 1,
                  padding: "14px",
                  background: "transparent",
                  border: "none",
                  color: P.t2,
                  fontSize: 7.5,
                  lineHeight: 1.8,
                  outline: "none",
                  resize: "none",
                  fontFamily: "'IBM Plex Mono',monospace",
                }}
              />
              <div style={{ padding: "10px 14px", borderTop: `1px solid ${P.b}`, display: "flex", gap: 8 }}>
                <button
                  onClick={handleCopyToClipboard}
                  style={{
                    flex: 1,
                    padding: "6px",
                    fontSize: 8,
                    fontWeight: 700,
                    cursor: "pointer",
                    background: `${P.teal}12`,
                    border: `1px solid ${P.teal}25`,
                    color: P.teal,
                    borderRadius: 7,
                  }}
                >
                  {copied ? "✓ Copied!" : "📋 Copy"}
                </button>
                <button
                  onClick={handleExportPDF}
                  style={{
                    flex: 1,
                    padding: "6px",
                    fontSize: 8,
                    fontWeight: 700,
                    cursor: "pointer",
                    background: `${P.violet}12`,
                    border: `1px solid ${P.violet}25`,
                    color: P.violet,
                    borderRadius: 7,
                  }}
                >
                  ↓ Export TXT
                </button>
                <input
                  value={recipientEmail}
                  onChange={(e) => setRecipientEmail(e.target.value)}
                  placeholder="CHC email"
                  style={{
                    flex: 1,
                    padding: "5px 8px",
                    fontSize: 7,
                    background: "#080D18",
                    border: `1px solid ${P.b}`,
                    color: P.t1,
                    borderRadius: 5,
                    outline: "none",
                  }}
                />
                <button
                  onClick={handleSendEmail}
                  disabled={sending}
                  style={{
                    flex: 1,
                    padding: "6px",
                    fontSize: 8,
                    fontWeight: 700,
                    cursor: sending ? "not-allowed" : "pointer",
                    background: `${P.amber}12`,
                    border: `1px solid ${P.amber}25`,
                    color: P.amber,
                    borderRadius: 7,
                    opacity: sending ? 0.5 : 1,
                  }}
                >
                  {sending ? "⟳ Sending..." : "📨 Email"}
                </button>
              </div>
            </>
          ) : (
            <div style={{ flex: 1, display: "flex", alignItems: "center", justifyContent: "center", padding: 30 }}>
              <div style={{ textAlign: "center" }}>
                <div style={{ fontSize: 24, marginBottom: 8 }}>📄</div>
                <div style={{ fontSize: 8, color: P.t4, lineHeight: 1.6 }}>
                  Select a critical case<br />
                  to generate an automated<br />
                  CHC inquiry letter
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}